In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import NeuralNetwork
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
btc_dfd = pd.read_csv('../Dataset/Binance_BTCUSDT_1h.csv')
btc_dfd

Date      Open      High       Low     Close  \
0      2022-12-31 23:00:00  16520.28  16551.24  16487.74  16542.40   
1      2022-12-31 22:00:00  16548.28  16567.49  16470.00  16520.81   
2      2022-12-31 21:00:00  16568.19  16571.64  16544.12  16548.28   
3      2022-12-31 20:00:00  16570.14  16574.97  16564.09  16568.60   
4      2022-12-31 19:00:00  16577.78  16590.06  16565.10  16570.14   
...                    ...       ...       ...       ...       ...   
26269  2020-01-01 04:00:00   7225.00   7230.00   7215.03   7217.27   
26270  2020-01-01 03:00:00   7242.66   7245.00   7220.00   7225.01   
26271  2020-01-01 02:00:00   7215.52   7244.87   7211.41   7242.85   
26272  2020-01-01 01:00:00   7176.47   7230.00   7175.71   7216.27   
26273  2020-01-01 00:00:00   7195.24   7196.25   7175.46   7177.02   

        Volume USDT  
0      8.217183e+07  
1      1.106669e+08  
2      5.992803e+07  
3      4.344849e+07  
4      6.704605e+07  
...             ...  
26269  3.379094e+06  
26270  5.667367e+06  
26271  4.736719e+06  
26272  6.365953e+06  
26273  3.675857e+06  

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(btc_dfd)
df

Date      Open      High       Low     Close  \
0      2020-01-01 00:00:00   7195.24   7196.25   7175.46   7177.02   
1      2020-01-01 01:00:00   7176.47   7230.00   7175.71   7216.27   
2      2020-01-01 02:00:00   7215.52   7244.87   7211.41   7242.85   
3      2020-01-01 03:00:00   7242.66   7245.00   7220.00   7225.01   
4      2020-01-01 04:00:00   7225.00   7230.00   7215.03   7217.27   
...                    ...       ...       ...       ...       ...   
26269  2022-12-31 19:00:00  16577.78  16590.06  16565.10  16570.14   
26270  2022-12-31 20:00:00  16570.14  16574.97  16564.09  16568.60   
26271  2022-12-31 21:00:00  16568.19  16571.64  16544.12  16548.28   
26272  2022-12-31 22:00:00  16548.28  16567.49  16470.00  16520.81   
26273  2022-12-31 23:00:00  16520.28  16551.24  16487.74  16542.40   

        Volume USDT  
0      3.675857e+06  
1      6.365953e+06  
2      4.736719e+06  
3      5.667367e+06  
4      3.379094e+06  
...             ...  
26269  6.704605e+07  
26270  4.344849e+07  
26271  5.992803e+07  
26272  1.106669e+08  
26273  8.217183e+07  

[26274 rows x 6 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.39451404, 0.38918512, 0.39751838, 0.01247029, 0.39344233],
       [0.39342821, 0.38742771, 0.39264325, 0.02946575, 0.3886748 ],
       [0.38866059, 0.38484765, 0.39034385, 0.03564371, 0.38670838]])

In [6]:
test

array([[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
       [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
       [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [7]:
train.shape

(21019, 5)

In [8]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [9]:
train_X

array([[[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
        [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        ...,
        [0.04809152, 0.04075928, 0.05263522, 0.00184419, 0.04755357],
        [0.04753806, 0.0402884 , 0.05246744, 0.00194012, 0.0475979 ],
        [0.0475869 , 0.04041777, 0.05262687, 0.00093754, 0.04775557]],

       [[0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.04797246],
        ...,
        [0.04753806, 0.0402884 , 0.05246744, 0.00194012, 0.0475979 ],
        [0.0475869 , 0.04041777, 0.05262687, 0.00093754, 0.04775557],
        [0.04774611, 0.04039696, 0.05262145, 0.00096387, 0.04744504]],

       [[0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.0

In [10]:
train_y

array([0.04744504, 0.04710444, 0.04649346, ..., 0.39344233, 0.3886748 ,
       0.38670838])

In [11]:
test_X

array([[[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
        [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        ...,
        [0.38279443, 0.37655397, 0.38229271, 0.02962508, 0.37981398],
        [0.37980004, 0.37607455, 0.38312154, 0.0179209 , 0.38255028],
        [0.38253615, 0.37634617, 0.38144779, 0.05495828, 0.37959724]],

       [[0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        ...,
        [0.37980004, 0.37607455, 0.38312154, 0.0179209 , 0.38255028],
        [0.38253615, 0.37634617, 0.38144779, 0.05495828, 0.37959724],
        [0.37958331, 0.37479453, 0.38374301, 0.01228897, 0.38068448]],

       [[0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.3

In [12]:
test_y

array([0.38068448, 0.38275027, 0.38296623, ..., 0.19251245, 0.19208658,
       0.19242129])

In [13]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 5) (20994,) (5230, 25, 5) (5230,)


In [14]:
train_X.shape[1]

25

In [15]:
train_X.shape[2]

5

## Model Training

In [16]:
hyperparams = []
batch = [16]
epoch = [25, 50, 100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(16, 25, 50),
 (16, 25, 60),
 (16, 25, 100),
 (16, 50, 50),
 (16, 50, 60),
 (16, 50, 100),
 (16, 100, 50),
 (16, 100, 60),
 (16, 100, 100)]

In [17]:
lstms1 = []
models1 = []
for batch, epoch, neuron in hyperparams:
    model, lstm = NeuralNetwork.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms1.append(lstm)
    models1.append(model)

Metal device set to: Apple M1
Epoch 1/25


2023-06-14 22:16:04.212646: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-06-14 22:16:04.213154: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-06-14 22:16:04.363243: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-06-14 22:16:05.298629: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:16:05.444655: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:16:05.457022: I tensorflow/core/grappler/o

1313/1313 - 27s - loss: 3.1597e-04 - val_loss: 0.0031 - 27s/epoch - 21ms/step
Epoch 2/25
1313/1313 - 25s - loss: 3.9681e-04 - val_loss: 0.0029 - 25s/epoch - 19ms/step
Epoch 3/25
1313/1313 - 25s - loss: 3.8434e-04 - val_loss: 0.0025 - 25s/epoch - 19ms/step
Epoch 4/25
1313/1313 - 25s - loss: 3.9626e-04 - val_loss: 0.0022 - 25s/epoch - 19ms/step
Epoch 5/25
1313/1313 - 25s - loss: 4.0687e-04 - val_loss: 0.0018 - 25s/epoch - 19ms/step
Epoch 6/25
1313/1313 - 25s - loss: 4.2350e-04 - val_loss: 0.0016 - 25s/epoch - 19ms/step
Epoch 7/25
1313/1313 - 25s - loss: 4.6183e-04 - val_loss: 0.0014 - 25s/epoch - 19ms/step
Epoch 8/25
1313/1313 - 25s - loss: 5.2146e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 9/25
1313/1313 - 25s - loss: 5.6919e-04 - val_loss: 7.2137e-04 - 25s/epoch - 19ms/step
Epoch 10/25
1313/1313 - 25s - loss: 6.0375e-04 - val_loss: 4.3596e-04 - 25s/epoch - 19ms/step
Epoch 11/25
1313/1313 - 25s - loss: 6.2860e-04 - val_loss: 2.5753e-04 - 25s/epoch - 19ms/step
Epoch 12/25
1313/1

2023-06-14 22:26:35.766465: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:26:35.903752: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:26:35.915646: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:26:36.040389: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:26:36.056330: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:26:58.534605: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:26:58.583870: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.4606e-04 - val_loss: 0.0018 - 27s/epoch - 20ms/step
Epoch 2/25
1313/1313 - 25s - loss: 3.0206e-04 - val_loss: 0.0026 - 25s/epoch - 19ms/step
Epoch 3/25
1313/1313 - 25s - loss: 3.3946e-04 - val_loss: 0.0024 - 25s/epoch - 19ms/step
Epoch 4/25
1313/1313 - 25s - loss: 3.2733e-04 - val_loss: 0.0021 - 25s/epoch - 19ms/step
Epoch 5/25
1313/1313 - 25s - loss: 3.3542e-04 - val_loss: 0.0018 - 25s/epoch - 19ms/step
Epoch 6/25
1313/1313 - 25s - loss: 3.5146e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 7/25
1313/1313 - 25s - loss: 3.6838e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 8/25
1313/1313 - 25s - loss: 4.0543e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 9/25
1313/1313 - 25s - loss: 4.8865e-04 - val_loss: 8.9078e-04 - 25s/epoch - 19ms/step
Epoch 10/25
1313/1313 - 25s - loss: 5.8765e-04 - val_loss: 6.1927e-04 - 25s/epoch - 19ms/step
Epoch 11/25
1313/1313 - 25s - loss: 6.8153e-04 - val_loss: 3.6836e-04 - 25s/epoch - 19ms/step
Epoch 12/25
1313/1

2023-06-14 22:37:02.477372: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:37:02.611385: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:37:02.623345: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:37:02.754263: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:37:02.770054: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:37:25.483321: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:37:25.531545: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.9285e-04 - val_loss: 0.0029 - 27s/epoch - 21ms/step
Epoch 2/25
1313/1313 - 25s - loss: 2.8626e-04 - val_loss: 0.0035 - 25s/epoch - 19ms/step
Epoch 3/25
1313/1313 - 26s - loss: 3.4467e-04 - val_loss: 0.0035 - 26s/epoch - 19ms/step
Epoch 4/25
1313/1313 - 25s - loss: 3.2623e-04 - val_loss: 0.0027 - 25s/epoch - 19ms/step
Epoch 5/25
1313/1313 - 25s - loss: 2.8700e-04 - val_loss: 0.0021 - 25s/epoch - 19ms/step
Epoch 6/25
1313/1313 - 25s - loss: 2.6385e-04 - val_loss: 0.0017 - 25s/epoch - 19ms/step
Epoch 7/25
1313/1313 - 25s - loss: 2.4922e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 8/25
1313/1313 - 25s - loss: 2.5658e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 9/25
1313/1313 - 25s - loss: 2.7918e-04 - val_loss: 0.0014 - 25s/epoch - 19ms/step
Epoch 10/25
1313/1313 - 26s - loss: 2.9918e-04 - val_loss: 0.0014 - 26s/epoch - 20ms/step
Epoch 11/25
1313/1313 - 25s - loss: 3.2237e-04 - val_loss: 0.0013 - 25s/epoch - 19ms/step
Epoch 12/25
1313/1313 - 25s - 

2023-06-14 22:47:36.387788: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:47:36.515333: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:47:36.527434: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:47:36.664147: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:47:36.681146: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:47:59.827265: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 22:47:59.877000: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 3.4516e-04 - val_loss: 0.0035 - 27s/epoch - 21ms/step
Epoch 2/50
1313/1313 - 26s - loss: 4.1763e-04 - val_loss: 0.0029 - 26s/epoch - 20ms/step
Epoch 3/50
1313/1313 - 26s - loss: 4.2592e-04 - val_loss: 0.0026 - 26s/epoch - 20ms/step
Epoch 4/50
1313/1313 - 26s - loss: 4.5802e-04 - val_loss: 0.0020 - 26s/epoch - 20ms/step
Epoch 5/50
1313/1313 - 26s - loss: 5.1448e-04 - val_loss: 0.0016 - 26s/epoch - 20ms/step
Epoch 6/50
1313/1313 - 26s - loss: 6.4045e-04 - val_loss: 0.0013 - 26s/epoch - 20ms/step
Epoch 7/50
1313/1313 - 26s - loss: 8.0681e-04 - val_loss: 8.1202e-04 - 26s/epoch - 20ms/step
Epoch 8/50
1313/1313 - 26s - loss: 9.6843e-04 - val_loss: 4.2978e-04 - 26s/epoch - 20ms/step
Epoch 9/50
1313/1313 - 25s - loss: 0.0010 - val_loss: 1.9437e-04 - 25s/epoch - 19ms/step
Epoch 10/50
1313/1313 - 25s - loss: 9.5491e-04 - val_loss: 9.7661e-05 - 25s/epoch - 19ms/step
Epoch 11/50
1313/1313 - 25s - loss: 8.2930e-04 - val_loss: 6.5956e-05 - 25s/epoch - 19ms/step
Epoch 12/50
13

2023-06-14 23:08:54.852920: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:08:54.982875: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:08:54.995090: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:08:55.131181: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:08:55.146852: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:09:17.996284: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:09:18.044038: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.5206e-04 - val_loss: 0.0019 - 27s/epoch - 21ms/step
Epoch 2/50
1313/1313 - 25s - loss: 3.4939e-04 - val_loss: 0.0027 - 25s/epoch - 19ms/step
Epoch 3/50
1313/1313 - 25s - loss: 3.7620e-04 - val_loss: 0.0024 - 25s/epoch - 19ms/step
Epoch 4/50
1313/1313 - 26s - loss: 4.0938e-04 - val_loss: 0.0020 - 26s/epoch - 19ms/step
Epoch 5/50
1313/1313 - 25s - loss: 4.6153e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 6/50
1313/1313 - 25s - loss: 5.7733e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 7/50
1313/1313 - 25s - loss: 7.3595e-04 - val_loss: 6.8747e-04 - 25s/epoch - 19ms/step
Epoch 8/50
1313/1313 - 25s - loss: 9.0178e-04 - val_loss: 3.2615e-04 - 25s/epoch - 19ms/step
Epoch 9/50
1313/1313 - 25s - loss: 9.7178e-04 - val_loss: 1.1422e-04 - 25s/epoch - 19ms/step
Epoch 10/50
1313/1313 - 25s - loss: 9.0062e-04 - val_loss: 5.2727e-05 - 25s/epoch - 19ms/step
Epoch 11/50
1313/1313 - 25s - loss: 7.8573e-04 - val_loss: 4.2943e-05 - 25s/epoch - 19ms/step
Epoch 12/5

2023-06-14 23:30:06.390877: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:30:06.552670: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:30:06.568811: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:30:06.729730: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:30:06.746106: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:30:30.005946: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:30:30.071788: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 28s - loss: 2.9898e-04 - val_loss: 0.0030 - 28s/epoch - 21ms/step
Epoch 2/50
1313/1313 - 26s - loss: 3.2313e-04 - val_loss: 0.0038 - 26s/epoch - 20ms/step
Epoch 3/50
1313/1313 - 26s - loss: 3.7927e-04 - val_loss: 0.0033 - 26s/epoch - 20ms/step
Epoch 4/50
1313/1313 - 26s - loss: 3.5330e-04 - val_loss: 0.0026 - 26s/epoch - 20ms/step
Epoch 5/50
1313/1313 - 26s - loss: 3.2731e-04 - val_loss: 0.0021 - 26s/epoch - 20ms/step
Epoch 6/50
1313/1313 - 26s - loss: 3.2503e-04 - val_loss: 0.0018 - 26s/epoch - 20ms/step
Epoch 7/50
1313/1313 - 25s - loss: 3.3462e-04 - val_loss: 0.0014 - 25s/epoch - 19ms/step
Epoch 8/50
1313/1313 - 26s - loss: 3.4919e-04 - val_loss: 0.0012 - 26s/epoch - 20ms/step
Epoch 9/50
1313/1313 - 25s - loss: 3.7465e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 10/50
1313/1313 - 25s - loss: 4.3069e-04 - val_loss: 9.6357e-04 - 25s/epoch - 19ms/step
Epoch 11/50
1313/1313 - 25s - loss: 5.0685e-04 - val_loss: 7.8009e-04 - 25s/epoch - 19ms/step
Epoch 12/50
1313/1313 

2023-06-14 23:51:22.314875: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:51:22.454822: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:51:22.467743: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:51:22.631132: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:51:22.647085: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:51:45.656974: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 23:51:45.705174: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 28s - loss: 3.6319e-04 - val_loss: 0.0035 - 28s/epoch - 21ms/step
Epoch 2/100
1313/1313 - 26s - loss: 4.4046e-04 - val_loss: 0.0030 - 26s/epoch - 20ms/step
Epoch 3/100
1313/1313 - 26s - loss: 4.4511e-04 - val_loss: 0.0028 - 26s/epoch - 20ms/step
Epoch 4/100
1313/1313 - 26s - loss: 4.6919e-04 - val_loss: 0.0021 - 26s/epoch - 20ms/step
Epoch 5/100
1313/1313 - 26s - loss: 4.9021e-04 - val_loss: 0.0016 - 26s/epoch - 19ms/step
Epoch 6/100
1313/1313 - 26s - loss: 5.6593e-04 - val_loss: 0.0013 - 26s/epoch - 19ms/step
Epoch 7/100
1313/1313 - 26s - loss: 6.9144e-04 - val_loss: 9.4184e-04 - 26s/epoch - 19ms/step
Epoch 8/100
1313/1313 - 26s - loss: 8.1614e-04 - val_loss: 5.8023e-04 - 26s/epoch - 19ms/step
Epoch 9/100
1313/1313 - 25s - loss: 9.3236e-04 - val_loss: 3.0263e-04 - 25s/epoch - 19ms/step
Epoch 10/100
1313/1313 - 26s - loss: 9.2512e-04 - val_loss: 1.4089e-04 - 26s/epoch - 19ms/step
Epoch 11/100
1313/1313 - 26s - loss: 8.3388e-04 - val_loss: 6.4796e-05 - 26s/epoch - 19ms/step


2023-06-15 00:33:55.598217: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 00:33:55.729857: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 00:33:55.742591: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 00:33:55.935214: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 00:33:55.950936: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 00:34:18.798838: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 00:34:18.846709: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.4161e-04 - val_loss: 0.0020 - 27s/epoch - 21ms/step
Epoch 2/100
1313/1313 - 25s - loss: 2.6832e-04 - val_loss: 0.0027 - 25s/epoch - 19ms/step
Epoch 3/100
1313/1313 - 25s - loss: 3.3595e-04 - val_loss: 0.0026 - 25s/epoch - 19ms/step
Epoch 4/100
1313/1313 - 25s - loss: 3.1228e-04 - val_loss: 0.0021 - 25s/epoch - 19ms/step
Epoch 5/100
1313/1313 - 25s - loss: 3.0506e-04 - val_loss: 0.0018 - 25s/epoch - 19ms/step
Epoch 6/100
1313/1313 - 25s - loss: 3.1951e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 7/100
1313/1313 - 25s - loss: 3.4836e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 8/100
1313/1313 - 25s - loss: 3.8016e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 9/100
1313/1313 - 25s - loss: 4.3535e-04 - val_loss: 8.3789e-04 - 25s/epoch - 19ms/step
Epoch 10/100
1313/1313 - 25s - loss: 5.2550e-04 - val_loss: 5.7080e-04 - 25s/epoch - 19ms/step
Epoch 11/100
1313/1313 - 25s - loss: 6.0032e-04 - val_loss: 3.3149e-04 - 25s/epoch - 19ms/step
Epoch 12

2023-06-15 01:15:48.938182: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 01:15:49.070782: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 01:15:49.083131: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 01:15:49.263459: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 01:15:49.279189: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 01:16:13.314523: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 01:16:13.363347: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 29s - loss: 3.0059e-04 - val_loss: 0.0031 - 29s/epoch - 22ms/step
Epoch 2/100
1313/1313 - 25s - loss: 3.0633e-04 - val_loss: 0.0035 - 25s/epoch - 19ms/step
Epoch 3/100
1313/1313 - 25s - loss: 3.8069e-04 - val_loss: 0.0033 - 25s/epoch - 19ms/step
Epoch 4/100
1313/1313 - 26s - loss: 3.8335e-04 - val_loss: 0.0026 - 26s/epoch - 19ms/step
Epoch 5/100
1313/1313 - 25s - loss: 4.0268e-04 - val_loss: 0.0021 - 25s/epoch - 19ms/step
Epoch 6/100
1313/1313 - 25s - loss: 4.4445e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 7/100
1313/1313 - 25s - loss: 5.3024e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 8/100
1313/1313 - 25s - loss: 6.8967e-04 - val_loss: 9.3140e-04 - 25s/epoch - 19ms/step
Epoch 9/100
1313/1313 - 25s - loss: 8.5555e-04 - val_loss: 5.3854e-04 - 25s/epoch - 19ms/step
Epoch 10/100
1313/1313 - 25s - loss: 9.9165e-04 - val_loss: 2.3356e-04 - 25s/epoch - 19ms/step
Epoch 11/100
1313/1313 - 25s - loss: 9.8134e-04 - val_loss: 7.5640e-05 - 25s/epoch - 19ms/step
Epoc

In [20]:
i=0
wb1 = Workbook()
ws1 = wb1.active
for m in models1:
    # make a prediction
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms1[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].layer.units))
    i = i+1
    ws1['A'+str(i)] = 'LSTM'
    ws1['B'+str(i)] = hyperparams[i-1][0]
    ws1['C'+str(i)] = hyperparams[i-1][1]
    ws1['D'+str(i)] = hyperparams[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat))
    ws1['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat))
    ws1['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat))
    ws1['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)
    NeuralNetwork.save_model(m, 1, 'BTC',hyperparams[i-1])
    with open('BiLSTM_BTC'+str(hyperparams[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms1[i-1].history, f)
wb1.save('BiLSTM_BTC_result1_16.xlsx')

164/164 [==============================] - 1s 9ms/step
(16, 25, 50)
Epoch: 25
Neurons: 50
RMSE
597.0932997844639
MAE
517.8894911119738
MAPE
2.7044522397055646
164/164 [==============================] - 1s 9ms/step
(16, 25, 60)
Epoch: 25
Neurons: 60
RMSE
273.85904009539627
MAE
208.97824867053
MAPE
1.0601157741686102
164/164 [==============================] - 1s 9ms/step
(16, 25, 100)
Epoch: 25
Neurons: 100
RMSE
1012.0618303617915
MAE
920.4090335205532
MAPE
4.805380112659433
164/164 [==============================] - 1s 8ms/step
(16, 50, 50)
Epoch: 50
Neurons: 50
RMSE
225.24136751727946
MAE
130.25404330485156
MAPE
0.6378329597140239
164/164 [==============================] - 1s 8ms/step
(16, 50, 60)
Epoch: 50
Neurons: 60
RMSE
242.16856391700404
MAE
137.21330388085568
MAPE
0.6758830510558
164/164 [==============================] - 1s 9ms/step
(16, 50, 100)
Epoch: 50
Neurons: 100
RMSE
286.61284908169074
MAE
175.7977170022708
MAPE
0.8513468061112263
164/164 [==============================] 

In [ ]:
test_X