In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import NeuralNetwork
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
eth_dfd = pd.read_csv('../Dataset/Binance_ETHUSDT_1h.csv')
eth_dfd

Date     Open     High      Low    Close   Volume USDT
0      2022-12-31 23:00:00  1196.18  1197.43  1193.60  1196.13  7.086714e+06
1      2022-12-31 22:00:00  1200.09  1201.11  1193.08  1196.19  1.143952e+07
2      2022-12-31 21:00:00  1202.33  1203.00  1199.83  1200.10  4.643401e+06
3      2022-12-31 20:00:00  1202.66  1203.71  1202.30  1202.34  4.278879e+06
4      2022-12-31 19:00:00  1199.59  1205.61  1199.42  1202.65  7.738029e+06
...                    ...      ...      ...      ...      ...           ...
26269  2020-01-01 04:00:00   130.21   130.74   130.15   130.20  4.430067e+05
26270  2020-01-01 03:00:00   130.85   130.89   129.94   130.20  6.473610e+05
26271  2020-01-01 02:00:00   130.63   130.98   130.35   130.85  9.940256e+05
26272  2020-01-01 01:00:00   128.87   130.65   128.78   130.64  1.474278e+06
26273  2020-01-01 00:00:00   129.16   129.19   128.68   128.87  1.000930e+06

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(eth_dfd)
df

Date     Open     High      Low    Close   Volume USDT
0      2020-01-01 00:00:00   129.16   129.19   128.68   128.87  1.000930e+06
1      2020-01-01 01:00:00   128.87   130.65   128.78   130.64  1.474278e+06
2      2020-01-01 02:00:00   130.63   130.98   130.35   130.85  9.940256e+05
3      2020-01-01 03:00:00   130.85   130.89   129.94   130.20  6.473610e+05
4      2020-01-01 04:00:00   130.21   130.74   130.15   130.20  4.430067e+05
...                    ...      ...      ...      ...      ...           ...
26269  2022-12-31 19:00:00  1199.59  1205.61  1199.42  1202.65  7.738029e+06
26270  2022-12-31 20:00:00  1202.66  1203.71  1202.30  1202.34  4.278879e+06
26271  2022-12-31 21:00:00  1202.33  1203.00  1199.83  1200.10  4.643401e+06
26272  2022-12-31 22:00:00  1200.09  1201.11  1193.08  1196.19  1.143952e+07
26273  2022-12-31 23:00:00  1196.18  1197.43  1193.60  1196.13  7.086714e+06

[26274 rows x 6 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
       [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
       [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
       ...,
       [0.23278314, 0.23041549, 0.23462933, 0.00396711, 0.23230718],
       [0.2323116 , 0.23001863, 0.23320743, 0.00977339, 0.23148404],
       [0.23148852, 0.22924589, 0.23331697, 0.00605456, 0.2314714 ]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
       [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
       [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
       ...,
       [0.36569953, 0.36527651, 0.3650033 , 0.03678181, 0.36294049],
       [0.36293557, 0.3619231 , 0.35881859, 0.0818867 , 0.35696376],
       [0.35696347, 0.35758067, 0.3546814 , 0.09563107, 0.35310278]])

In [6]:
test

array([[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
       [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
       [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
       ...,
       [0.23278314, 0.23041549, 0.23462933, 0.00396711, 0.23230718],
       [0.2323116 , 0.23001863, 0.23320743, 0.00977339, 0.23148404],
       [0.23148852, 0.22924589, 0.23331697, 0.00605456, 0.2314714 ]])

In [7]:
train.shape

(21019, 5)

In [8]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [9]:
train_X

array([[[6.87306202e-03, 4.93458007e-03, 8.99058180e-03, 8.55147771e-04,
         6.78934504e-03],
        [6.81201491e-03, 5.24115398e-03, 9.01164689e-03, 1.25955490e-03,
         7.16196956e-03],
        [7.18250769e-03, 5.31044808e-03, 9.34236885e-03, 8.49249206e-04,
         7.20617925e-03],
        ...,
        [7.43301133e-03, 5.48683307e-03, 9.24757593e-03, 1.66032651e-03,
         7.08407630e-03],
        [7.10883015e-03, 5.28735005e-03, 9.21387179e-03, 4.30213606e-04,
         7.18933747e-03],
        [7.20145334e-03, 5.26845165e-03, 9.32551678e-03, 4.20791873e-04,
         7.16828523e-03]],

       [[6.81201491e-03, 5.24115398e-03, 9.01164689e-03, 1.25955490e-03,
         7.16196956e-03],
        [7.18250769e-03, 5.31044808e-03, 9.34236885e-03, 8.49249206e-04,
         7.20617925e-03],
        [7.22881929e-03, 5.29154969e-03, 9.25600197e-03, 5.53075059e-04,
         7.06933974e-03],
        ...,
        [7.10883015e-03, 5.28735005e-03, 9.21387179e-03, 4.30213606e-04,
        

In [10]:
train_y

array([0.00705881, 0.00696829, 0.00683777, ..., 0.36294049, 0.35696376,
       0.35310278])

In [11]:
test_X

array([[[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
        [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        ...,
        [0.34641496, 0.34422371, 0.34062256, 0.07658457, 0.34328823],
        [0.34328471, 0.34513503, 0.34467969, 0.05165182, 0.34773236],
        [0.34772852, 0.34577757, 0.34559181, 0.05109385, 0.34391769]],

       [[0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        ...,
        [0.34328471, 0.34513503, 0.34467969, 0.05165182, 0.34773236],
        [0.34772852, 0.34577757, 0.34559181, 0.05109385, 0.34391769],
        [0.34391623, 0.34358956, 0.34482294, 0.03178197, 0.34373243]],

       [[0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.3

In [12]:
test_y

array([0.34373243, 0.35124808, 0.35062494, ..., 0.23230718, 0.23148404,
       0.2314714 ])

In [13]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 5) (20994,) (5230, 25, 5) (5230,)


In [14]:
train_X.shape[1]

25

In [15]:
train_X.shape[2]

5

## Model Training

In [16]:
hyperparams = []
batch = [16]
epoch = [25, 50, 100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(16, 25, 50),
 (16, 25, 60),
 (16, 25, 100),
 (16, 50, 50),
 (16, 50, 60),
 (16, 50, 100),
 (16, 100, 50),
 (16, 100, 60),
 (16, 100, 100)]

In [17]:
lstms1 = []
models1 = []
for batch, epoch, neuron in hyperparams:
    model, lstm = NeuralNetwork.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms1.append(lstm)
    models1.append(model)

Metal device set to: Apple M1
Epoch 1/25


2023-06-15 07:44:44.475465: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-06-15 07:44:44.475719: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-06-15 07:44:44.583839: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-06-15 07:44:45.498612: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:44:45.641248: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:44:45.653563: I tensorflow/core/grappler/o

1313/1313 - 27s - loss: 4.1397e-04 - val_loss: 0.0031 - 27s/epoch - 21ms/step
Epoch 2/25
1313/1313 - 25s - loss: 4.5037e-04 - val_loss: 0.0020 - 25s/epoch - 19ms/step
Epoch 3/25
1313/1313 - 25s - loss: 4.4583e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 4/25
1313/1313 - 25s - loss: 4.5767e-04 - val_loss: 0.0013 - 25s/epoch - 19ms/step
Epoch 5/25
1313/1313 - 25s - loss: 5.0921e-04 - val_loss: 0.0010 - 25s/epoch - 19ms/step
Epoch 6/25
1313/1313 - 25s - loss: 6.3351e-04 - val_loss: 7.2185e-04 - 25s/epoch - 19ms/step
Epoch 7/25
1313/1313 - 25s - loss: 8.5337e-04 - val_loss: 3.3970e-04 - 25s/epoch - 19ms/step
Epoch 8/25
1313/1313 - 25s - loss: 9.8657e-04 - val_loss: 1.4553e-04 - 25s/epoch - 19ms/step
Epoch 9/25
1313/1313 - 25s - loss: 9.3681e-04 - val_loss: 8.0620e-05 - 25s/epoch - 19ms/step
Epoch 10/25
1313/1313 - 25s - loss: 8.2474e-04 - val_loss: 5.8155e-05 - 25s/epoch - 19ms/step
Epoch 11/25
1313/1313 - 25s - loss: 6.7552e-04 - val_loss: 6.3584e-05 - 25s/epoch - 19ms/step
Epoch 

2023-06-15 07:55:17.546907: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:55:17.686018: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:55:17.697869: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:55:17.824624: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:55:17.840373: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:55:40.412667: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 07:55:40.463627: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.7295e-04 - val_loss: 0.0023 - 27s/epoch - 20ms/step
Epoch 2/25
1313/1313 - 25s - loss: 2.6558e-04 - val_loss: 0.0019 - 25s/epoch - 19ms/step
Epoch 3/25
1313/1313 - 25s - loss: 2.4951e-04 - val_loss: 0.0017 - 25s/epoch - 19ms/step
Epoch 4/25
1313/1313 - 25s - loss: 2.5302e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 5/25
1313/1313 - 25s - loss: 2.5709e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 6/25
1313/1313 - 25s - loss: 2.7992e-04 - val_loss: 0.0010 - 25s/epoch - 19ms/step
Epoch 7/25
1313/1313 - 25s - loss: 3.1093e-04 - val_loss: 8.3626e-04 - 25s/epoch - 19ms/step
Epoch 8/25
1313/1313 - 25s - loss: 3.5831e-04 - val_loss: 7.1030e-04 - 25s/epoch - 19ms/step
Epoch 9/25
1313/1313 - 25s - loss: 4.4807e-04 - val_loss: 4.9903e-04 - 25s/epoch - 19ms/step
Epoch 10/25
1313/1313 - 25s - loss: 6.2019e-04 - val_loss: 1.9363e-04 - 25s/epoch - 19ms/step
Epoch 11/25
1313/1313 - 25s - loss: 7.8852e-04 - val_loss: 5.9738e-05 - 25s/epoch - 19ms/step
Epoch 12/2

2023-06-15 08:05:46.154391: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:05:46.287855: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:05:46.299745: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:05:46.439632: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:05:46.455336: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:06:09.362302: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:06:09.412821: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.7844e-04 - val_loss: 0.0032 - 27s/epoch - 21ms/step
Epoch 2/25
1313/1313 - 25s - loss: 2.9805e-04 - val_loss: 0.0027 - 25s/epoch - 19ms/step
Epoch 3/25
1313/1313 - 25s - loss: 2.6645e-04 - val_loss: 0.0022 - 25s/epoch - 19ms/step
Epoch 4/25
1313/1313 - 25s - loss: 2.4117e-04 - val_loss: 0.0020 - 25s/epoch - 19ms/step
Epoch 5/25
1313/1313 - 25s - loss: 2.3356e-04 - val_loss: 0.0017 - 25s/epoch - 19ms/step
Epoch 6/25
1313/1313 - 25s - loss: 2.3563e-04 - val_loss: 0.0014 - 25s/epoch - 19ms/step
Epoch 7/25
1313/1313 - 25s - loss: 2.4426e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 8/25
1313/1313 - 25s - loss: 2.6850e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 9/25
1313/1313 - 25s - loss: 2.9280e-04 - val_loss: 9.8104e-04 - 25s/epoch - 19ms/step
Epoch 10/25
1313/1313 - 25s - loss: 3.1484e-04 - val_loss: 8.5269e-04 - 25s/epoch - 19ms/step
Epoch 11/25
1313/1313 - 25s - loss: 3.4365e-04 - val_loss: 7.7932e-04 - 25s/epoch - 19ms/step
Epoch 12/25
1313/1

2023-06-15 08:16:12.693762: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:16:12.830805: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:16:12.843082: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:16:12.986248: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:16:13.001970: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:16:35.954711: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:16:36.007507: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 4.1947e-04 - val_loss: 0.0028 - 27s/epoch - 21ms/step
Epoch 2/50
1313/1313 - 25s - loss: 4.5780e-04 - val_loss: 0.0019 - 25s/epoch - 19ms/step
Epoch 3/50
1313/1313 - 25s - loss: 4.4361e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 4/50
1313/1313 - 25s - loss: 4.4970e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 5/50
1313/1313 - 25s - loss: 4.8980e-04 - val_loss: 9.9884e-04 - 25s/epoch - 19ms/step
Epoch 6/50
1313/1313 - 25s - loss: 5.8724e-04 - val_loss: 7.6384e-04 - 25s/epoch - 19ms/step
Epoch 7/50
1313/1313 - 25s - loss: 7.6085e-04 - val_loss: 4.3398e-04 - 25s/epoch - 19ms/step
Epoch 8/50
1313/1313 - 25s - loss: 8.9311e-04 - val_loss: 2.1624e-04 - 25s/epoch - 19ms/step
Epoch 9/50
1313/1313 - 25s - loss: 8.7832e-04 - val_loss: 1.2934e-04 - 25s/epoch - 19ms/step
Epoch 10/50
1313/1313 - 25s - loss: 7.7848e-04 - val_loss: 8.9557e-05 - 25s/epoch - 19ms/step
Epoch 11/50
1313/1313 - 25s - loss: 6.5128e-04 - val_loss: 6.5732e-05 - 25s/epoch - 19ms/step
Ep

2023-06-15 08:37:20.744072: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:37:20.876343: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:37:20.888642: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:37:21.048507: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:37:21.064055: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:37:43.916517: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:37:43.972792: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 2.6686e-04 - val_loss: 0.0023 - 27s/epoch - 21ms/step
Epoch 2/50
1313/1313 - 26s - loss: 2.6413e-04 - val_loss: 0.0020 - 26s/epoch - 19ms/step
Epoch 3/50
1313/1313 - 25s - loss: 2.5583e-04 - val_loss: 0.0018 - 25s/epoch - 19ms/step
Epoch 4/50
1313/1313 - 25s - loss: 2.5615e-04 - val_loss: 0.0016 - 25s/epoch - 19ms/step
Epoch 5/50
1313/1313 - 25s - loss: 2.5494e-04 - val_loss: 0.0013 - 25s/epoch - 19ms/step
Epoch 6/50
1313/1313 - 25s - loss: 2.6305e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 7/50
1313/1313 - 25s - loss: 2.8265e-04 - val_loss: 8.7665e-04 - 25s/epoch - 19ms/step
Epoch 8/50
1313/1313 - 25s - loss: 3.0516e-04 - val_loss: 7.6336e-04 - 25s/epoch - 19ms/step
Epoch 9/50
1313/1313 - 25s - loss: 3.4588e-04 - val_loss: 6.6048e-04 - 25s/epoch - 19ms/step
Epoch 10/50
1313/1313 - 25s - loss: 4.2099e-04 - val_loss: 5.1112e-04 - 25s/epoch - 19ms/step
Epoch 11/50
1313/1313 - 25s - loss: 5.4926e-04 - val_loss: 2.8751e-04 - 25s/epoch - 19ms/step
Epoch 12/5

2023-06-15 08:58:01.929950: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:58:02.065248: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:58:02.078711: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:58:02.243922: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:58:02.259367: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:58:25.287484: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 08:58:25.335130: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 27s - loss: 3.0740e-04 - val_loss: 0.0033 - 27s/epoch - 21ms/step
Epoch 2/50
1313/1313 - 25s - loss: 3.2583e-04 - val_loss: 0.0027 - 25s/epoch - 19ms/step
Epoch 3/50
1313/1313 - 25s - loss: 3.0131e-04 - val_loss: 0.0023 - 25s/epoch - 19ms/step
Epoch 4/50
1313/1313 - 26s - loss: 2.7564e-04 - val_loss: 0.0019 - 26s/epoch - 19ms/step
Epoch 5/50
1313/1313 - 25s - loss: 2.6995e-04 - val_loss: 0.0015 - 25s/epoch - 19ms/step
Epoch 6/50
1313/1313 - 25s - loss: 2.7720e-04 - val_loss: 0.0013 - 25s/epoch - 19ms/step
Epoch 7/50
1313/1313 - 25s - loss: 3.0423e-04 - val_loss: 0.0011 - 25s/epoch - 19ms/step
Epoch 8/50
1313/1313 - 25s - loss: 3.2958e-04 - val_loss: 8.9227e-04 - 25s/epoch - 19ms/step
Epoch 9/50
1313/1313 - 25s - loss: 3.6266e-04 - val_loss: 7.3446e-04 - 25s/epoch - 19ms/step
Epoch 10/50
1313/1313 - 25s - loss: 4.1720e-04 - val_loss: 5.5776e-04 - 25s/epoch - 19ms/step
Epoch 11/50
1313/1313 - 25s - loss: 5.1166e-04 - val_loss: 3.4744e-04 - 25s/epoch - 19ms/step
Epoch 12/50
13

2023-06-15 09:19:03.366974: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 09:19:03.513295: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 09:19:03.525506: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 09:19:03.709032: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 09:19:03.725044: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 09:19:27.694397: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 09:19:27.743586: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 29s - loss: 3.8021e-04 - val_loss: 0.0031 - 29s/epoch - 22ms/step
Epoch 2/100
1313/1313 - 25s - loss: 4.0915e-04 - val_loss: 0.0021 - 25s/epoch - 19ms/step
Epoch 3/100
1313/1313 - 25s - loss: 3.8495e-04 - val_loss: 0.0016 - 25s/epoch - 19ms/step
Epoch 4/100
1313/1313 - 26s - loss: 3.7608e-04 - val_loss: 0.0013 - 26s/epoch - 20ms/step
Epoch 5/100
1313/1313 - 26s - loss: 3.8358e-04 - val_loss: 0.0012 - 26s/epoch - 19ms/step
Epoch 6/100
1313/1313 - 25s - loss: 4.1343e-04 - val_loss: 9.4464e-04 - 25s/epoch - 19ms/step
Epoch 7/100
1313/1313 - 25s - loss: 4.8335e-04 - val_loss: 7.8742e-04 - 25s/epoch - 19ms/step
Epoch 8/100
1313/1313 - 25s - loss: 6.2445e-04 - val_loss: 4.9931e-04 - 25s/epoch - 19ms/step
Epoch 9/100
1313/1313 - 25s - loss: 7.7045e-04 - val_loss: 2.4142e-04 - 25s/epoch - 19ms/step
Epoch 10/100
1313/1313 - 25s - loss: 8.3259e-04 - val_loss: 1.1661e-04 - 25s/epoch - 19ms/step
Epoch 11/100
1313/1313 - 25s - loss: 7.7202e-04 - val_loss: 6.8481e-05 - 25s/epoch - 19ms/s

2023-06-15 10:01:03.313063: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:01:03.477084: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:01:03.492815: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:01:03.657592: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:01:03.673653: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:01:27.182355: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:01:27.235460: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 28s - loss: 2.7329e-04 - val_loss: 0.0023 - 28s/epoch - 21ms/step
Epoch 2/100
1313/1313 - 26s - loss: 2.7400e-04 - val_loss: 0.0020 - 26s/epoch - 20ms/step
Epoch 3/100
1313/1313 - 26s - loss: 2.5562e-04 - val_loss: 0.0017 - 26s/epoch - 20ms/step
Epoch 4/100
1313/1313 - 26s - loss: 2.5095e-04 - val_loss: 0.0014 - 26s/epoch - 20ms/step
Epoch 5/100
1313/1313 - 26s - loss: 2.5445e-04 - val_loss: 0.0012 - 26s/epoch - 20ms/step
Epoch 6/100
1313/1313 - 26s - loss: 2.8246e-04 - val_loss: 0.0010 - 26s/epoch - 20ms/step
Epoch 7/100
1313/1313 - 26s - loss: 3.1414e-04 - val_loss: 8.3281e-04 - 26s/epoch - 20ms/step
Epoch 8/100
1313/1313 - 26s - loss: 3.6036e-04 - val_loss: 6.7255e-04 - 26s/epoch - 20ms/step
Epoch 9/100
1313/1313 - 26s - loss: 4.3491e-04 - val_loss: 5.1108e-04 - 26s/epoch - 20ms/step
Epoch 10/100
1313/1313 - 26s - loss: 5.6373e-04 - val_loss: 2.6740e-04 - 26s/epoch - 20ms/step
Epoch 11/100
1313/1313 - 26s - loss: 6.9122e-04 - val_loss: 8.6159e-05 - 26s/epoch - 20ms/step


2023-06-15 10:43:42.006426: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:43:42.138360: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:43:42.152353: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:43:42.317580: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:43:42.333105: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:44:05.407356: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 10:44:05.459635: I tensorflow/core/grappler/optimizers/cust

1313/1313 - 28s - loss: 3.1218e-04 - val_loss: 0.0034 - 28s/epoch - 21ms/step
Epoch 2/100
1313/1313 - 25s - loss: 3.3682e-04 - val_loss: 0.0028 - 25s/epoch - 19ms/step
Epoch 3/100
1313/1313 - 25s - loss: 3.1166e-04 - val_loss: 0.0023 - 25s/epoch - 19ms/step
Epoch 4/100
1313/1313 - 25s - loss: 3.0171e-04 - val_loss: 0.0017 - 25s/epoch - 19ms/step
Epoch 5/100
1313/1313 - 25s - loss: 2.9650e-04 - val_loss: 0.0014 - 25s/epoch - 19ms/step
Epoch 6/100
1313/1313 - 25s - loss: 3.2447e-04 - val_loss: 0.0012 - 25s/epoch - 19ms/step
Epoch 7/100
1313/1313 - 25s - loss: 3.6101e-04 - val_loss: 0.0010 - 25s/epoch - 19ms/step
Epoch 8/100
1313/1313 - 26s - loss: 4.1845e-04 - val_loss: 7.7775e-04 - 26s/epoch - 20ms/step
Epoch 9/100
1313/1313 - 26s - loss: 5.1543e-04 - val_loss: 5.0720e-04 - 26s/epoch - 20ms/step
Epoch 10/100
1313/1313 - 25s - loss: 6.6586e-04 - val_loss: 2.2747e-04 - 25s/epoch - 19ms/step
Epoch 11/100
1313/1313 - 25s - loss: 7.9640e-04 - val_loss: 7.8122e-05 - 25s/epoch - 19ms/step
Epoc

In [18]:
i=0
wb1 = Workbook()
ws1 = wb1.active
for m in models1:
    # make a prediction
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms1[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].layer.units))
    i = i+1
    ws1['A'+str(i)] = 'LSTM'
    ws1['B'+str(i)] = hyperparams[i-1][0]
    ws1['C'+str(i)] = hyperparams[i-1][1]
    ws1['D'+str(i)] = hyperparams[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat))
    ws1['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat))
    ws1['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat))
    ws1['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)
    NeuralNetwork.save_model(m, 1, 'ETH',hyperparams[i-1])
    with open('BiLSTM_ETH'+str(hyperparams[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms1[i-1].history, f)
wb1.save('BiLSTM_ETH_result1_16.xlsx')

2023-06-15 11:25:46.931820: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:47.020651: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:47.030412: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 9ms/step
(16, 25, 50)
Epoch: 25
Neurons: 50
RMSE
16.013290993793238
MAE
10.887927377266832
MAPE
0.788075275550597


2023-06-15 11:25:49.038148: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:49.091412: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:49.100253: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 9ms/step
(16, 25, 60)
Epoch: 25
Neurons: 60
RMSE
15.987912496027006
MAE
10.178618821328284
MAPE
0.7103089187213424


2023-06-15 11:25:51.015758: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:51.067623: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:51.076657: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 25, 100)
Epoch: 25
Neurons: 100
RMSE
40.18482301111503
MAE
36.183264713323744
MAPE
2.7500425802297728


2023-06-15 11:25:53.069412: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:53.114323: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:53.123342: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 50, 50)
Epoch: 50
Neurons: 50
RMSE
14.582733670320684
MAE
9.560822972839281
MAPE
0.6820987151836713


2023-06-15 11:25:55.105191: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:55.158024: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:55.166981: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 50, 60)
Epoch: 50
Neurons: 60
RMSE
14.667121416630538
MAE
10.046771116997064
MAPE
0.7256957200312676


2023-06-15 11:25:57.138837: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:57.185460: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:57.194309: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 50, 100)
Epoch: 50
Neurons: 100
RMSE
16.31096062369741
MAE
12.330772037075809
MAPE
0.9176555630937154


2023-06-15 11:25:59.194951: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:59.243737: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:25:59.252891: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 100, 50)
Epoch: 100
Neurons: 50
RMSE
23.60341672109596
MAE
20.161300771446978
MAPE
1.5233946794804256


2023-06-15 11:26:01.276041: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:26:01.321551: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:26:01.330717: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 100, 60)
Epoch: 100
Neurons: 60
RMSE
14.926214831892533
MAE
10.820018956609292
MAPE
0.7938300561377324


2023-06-15 11:26:03.313447: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:26:03.363575: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 11:26:03.372639: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 10ms/step
(16, 100, 100)
Epoch: 100
Neurons: 100
RMSE
27.17410526867205
MAE
23.729902270461082
MAPE
1.817965923580856


In [19]:
test_X

array([[[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
        [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        ...,
        [0.34641496, 0.34422371, 0.34062256, 0.07658457, 0.34328823],
        [0.34328471, 0.34513503, 0.34467969, 0.05165182, 0.34773236],
        [0.34772852, 0.34577757, 0.34559181, 0.05109385, 0.34391769]],

       [[0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        ...,
        [0.34328471, 0.34513503, 0.34467969, 0.05165182, 0.34773236],
        [0.34772852, 0.34577757, 0.34559181, 0.05109385, 0.34391769],
        [0.34391623, 0.34358956, 0.34482294, 0.03178197, 0.34373243]],

       [[0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.3