In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import NeuralNetwork
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
ltc_dfd = pd.read_csv('../Dataset/Binance_LTCUSDT_1h.csv')
ltc_dfd

Date   Open   High    Low  Close   Volume USDT
0      2022-12-31 23:00:00  70.08  70.30  69.79  70.14  9.486568e+05
1      2022-12-31 22:00:00  70.24  70.24  69.71  70.09  8.838422e+05
2      2022-12-31 21:00:00  70.40  70.45  70.19  70.23  6.820723e+05
3      2022-12-31 20:00:00  70.15  70.53  70.08  70.39  1.173164e+06
4      2022-12-31 19:00:00  69.93  70.32  69.93  70.15  9.964355e+05
...                    ...    ...    ...    ...    ...           ...
26269  2020-01-01 04:00:00  41.53  41.85  41.45  41.59  2.214516e+05
26270  2020-01-01 03:00:00  41.84  41.85  41.49  41.53  1.613043e+05
26271  2020-01-01 02:00:00  41.63  41.88  41.62  41.85  2.402871e+05
26272  2020-01-01 01:00:00  41.28  41.70  41.27  41.62  2.830715e+05
26273  2020-01-01 00:00:00  41.29  41.29  41.16  41.28  1.165827e+05

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(ltc_dfd)
df

Date   Open   High    Low  Close   Volume USDT
0      2020-01-01 00:00:00  41.29  41.29  41.16  41.28  1.165827e+05
1      2020-01-01 01:00:00  41.28  41.70  41.27  41.62  2.830715e+05
2      2020-01-01 02:00:00  41.63  41.88  41.62  41.85  2.402871e+05
3      2020-01-01 03:00:00  41.84  41.85  41.49  41.53  1.613043e+05
4      2020-01-01 04:00:00  41.53  41.85  41.45  41.59  2.214516e+05
...                    ...    ...    ...    ...    ...           ...
26269  2022-12-31 19:00:00  69.93  70.32  69.93  70.15  9.964355e+05
26270  2022-12-31 20:00:00  70.15  70.53  70.08  70.39  1.173164e+06
26271  2022-12-31 21:00:00  70.40  70.45  70.19  70.23  6.820723e+05
26272  2022-12-31 22:00:00  70.24  70.24  69.71  70.09  8.838422e+05
26273  2022-12-31 23:00:00  70.08  70.30  69.79  70.14  9.486568e+05

[26274 rows x 6 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
       [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
       [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
       ...,
       [0.11742375, 0.10675971, 0.1219377 , 0.00159586, 0.11697868],
       [0.11700772, 0.10621289, 0.12067054, 0.00206794, 0.11661466],
       [0.1165917 , 0.10636913, 0.12088173, 0.00221959, 0.11674467]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
       [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
       [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
       ...,
       [0.10182272, 0.09230809, 0.1061246 , 0.00158488, 0.10208008],
       [0.10182272, 0.09178731, 0.10374868, 0.00463816, 0.09947998],
       [0.09922255, 0.09022498, 0.10295671, 0.00463943, 0.09869995]])

In [6]:
test

array([[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
       [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
       [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
       ...,
       [0.11742375, 0.10675971, 0.1219377 , 0.00159586, 0.11697868],
       [0.11700772, 0.10621289, 0.12067054, 0.00206794, 0.11661466],
       [0.1165917 , 0.10636913, 0.12088173, 0.00221959, 0.11674467]])

In [7]:
train.shape

(21019, 5)

In [8]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [9]:
train_X

array([[[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
        [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
        [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        ...,
        [0.04266882, 0.03179356, 0.04580253, 0.00063111, 0.04230369],
        [0.04227879, 0.03176752, 0.04572334, 0.00034972, 0.0425897 ],
        [0.0424868 , 0.03200187, 0.04627772, 0.00024796, 0.04290172]],

       [[0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
        [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        ...,
        [0.04227879, 0.03176752, 0.04572334, 0.00034972, 0.0425897 ],
        [0.0424868 , 0.03200187, 0.04627772, 0.00024796, 0.04290172],
        [0.04290283, 0.03200187, 0.04619852, 0.00014903, 0.0423817 ]],

       [[0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.0

In [10]:
train_y

array([0.0423817 , 0.04193968, 0.04144566, ..., 0.10208008, 0.09947998,
       0.09869995])

In [11]:
test_X

array([[[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
        [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        ...,
        [0.09558231, 0.08501719, 0.09767687, 0.00433742, 0.09453978],
        [0.09454224, 0.0871003 , 0.09846885, 0.00441158, 0.0973999 ],
        [0.09714241, 0.08683991, 0.09846885, 0.0045675 , 0.09453978]],

       [[0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        ...,
        [0.09454224, 0.0871003 , 0.09846885, 0.00441158, 0.0973999 ],
        [0.09714241, 0.08683991, 0.09846885, 0.0045675 , 0.09453978],
        [0.09454224, 0.08501719, 0.09846885, 0.00252454, 0.09479979]],

       [[0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.0

In [12]:
test_y

array([0.09479979, 0.09635985, 0.0973999 , ..., 0.11697868, 0.11661466,
       0.11674467])

In [13]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 5) (20994,) (5230, 25, 5) (5230,)


In [14]:
train_X.shape[1]

25

In [15]:
train_X.shape[2]

5

## Model Training

In [16]:
hyperparams = []
batch = [16]
epoch = [25, 50, 100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(16, 25, 50),
 (16, 25, 60),
 (16, 25, 100),
 (16, 50, 50),
 (16, 50, 60),
 (16, 50, 100),
 (16, 100, 50),
 (16, 100, 60),
 (16, 100, 100)]

In [17]:
lstms1 = []
models1 = []
for batch, epoch, neuron in hyperparams:
    model, lstm = NeuralNetwork.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms1.append(lstm)
    models1.append(model)

Metal device set to: Apple M1


2023-06-15 23:53:55.585618: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-06-15 23:53:55.586084: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/25


2023-06-15 23:53:55.888275: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-06-15 23:53:56.290975: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 23:53:56.394420: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 23:53:56.596705: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 23:54:09.342296: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 23:54:09.371815: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 2.1939e-04 - val_loss: 8.1191e-05 - 15s/epoch - 12ms/step
Epoch 2/25
1313/1313 - 14s - loss: 1.6331e-04 - val_loss: 7.9228e-05 - 14s/epoch - 11ms/step
Epoch 3/25
1313/1313 - 14s - loss: 1.4932e-04 - val_loss: 7.1880e-05 - 14s/epoch - 11ms/step
Epoch 4/25
1313/1313 - 14s - loss: 1.3258e-04 - val_loss: 6.5231e-05 - 14s/epoch - 11ms/step
Epoch 5/25
1313/1313 - 14s - loss: 1.1683e-04 - val_loss: 5.8883e-05 - 14s/epoch - 11ms/step
Epoch 6/25
1313/1313 - 14s - loss: 1.0178e-04 - val_loss: 5.3472e-05 - 14s/epoch - 11ms/step
Epoch 7/25
1313/1313 - 14s - loss: 8.9115e-05 - val_loss: 4.9449e-05 - 14s/epoch - 11ms/step
Epoch 8/25
1313/1313 - 14s - loss: 7.8435e-05 - val_loss: 4.7258e-05 - 14s/epoch - 11ms/step
Epoch 9/25
1313/1313 - 14s - loss: 7.0088e-05 - val_loss: 4.6041e-05 - 14s/epoch - 11ms/step
Epoch 10/25
1313/1313 - 14s - loss: 6.4033e-05 - val_loss: 4.6001e-05 - 14s/epoch - 11ms/step
Epoch 11/25
1313/1313 - 14s - loss: 6.0171e-05 - val_loss: 4.7208e-05 - 14s/epoc

2023-06-15 23:59:47.590785: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 23:59:47.685937: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-15 23:59:47.788391: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:00:00.374011: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:00:00.411321: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.9945e-04 - val_loss: 8.8210e-05 - 15s/epoch - 11ms/step
Epoch 2/25
1313/1313 - 14s - loss: 1.6290e-04 - val_loss: 8.2656e-05 - 14s/epoch - 11ms/step
Epoch 3/25
1313/1313 - 14s - loss: 1.6393e-04 - val_loss: 7.7423e-05 - 14s/epoch - 11ms/step
Epoch 4/25
1313/1313 - 14s - loss: 1.6277e-04 - val_loss: 6.9291e-05 - 14s/epoch - 11ms/step
Epoch 5/25
1313/1313 - 14s - loss: 1.5545e-04 - val_loss: 6.0548e-05 - 14s/epoch - 11ms/step
Epoch 6/25
1313/1313 - 14s - loss: 1.4484e-04 - val_loss: 5.1991e-05 - 14s/epoch - 11ms/step
Epoch 7/25
1313/1313 - 14s - loss: 1.3334e-04 - val_loss: 4.3671e-05 - 14s/epoch - 11ms/step
Epoch 8/25
1313/1313 - 14s - loss: 1.2113e-04 - val_loss: 3.6441e-05 - 14s/epoch - 11ms/step
Epoch 9/25
1313/1313 - 14s - loss: 1.1058e-04 - val_loss: 3.0299e-05 - 14s/epoch - 11ms/step
Epoch 10/25
1313/1313 - 14s - loss: 1.0034e-04 - val_loss: 2.4980e-05 - 14s/epoch - 11ms/step
Epoch 11/25
1313/1313 - 14s - loss: 9.2534e-05 - val_loss: 2.1090e-05 - 14s/epoc

2023-06-16 00:05:36.108167: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:05:36.189091: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:05:36.283998: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:05:48.911471: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:05:48.941400: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 2.1651e-04 - val_loss: 1.2284e-04 - 15s/epoch - 11ms/step
Epoch 2/25
1313/1313 - 14s - loss: 1.7745e-04 - val_loss: 1.1315e-04 - 14s/epoch - 11ms/step
Epoch 3/25
1313/1313 - 14s - loss: 1.6668e-04 - val_loss: 1.0469e-04 - 14s/epoch - 11ms/step
Epoch 4/25
1313/1313 - 14s - loss: 1.4883e-04 - val_loss: 9.6535e-05 - 14s/epoch - 11ms/step
Epoch 5/25
1313/1313 - 14s - loss: 1.2972e-04 - val_loss: 8.4081e-05 - 14s/epoch - 11ms/step
Epoch 6/25
1313/1313 - 14s - loss: 1.1088e-04 - val_loss: 7.2254e-05 - 14s/epoch - 11ms/step
Epoch 7/25
1313/1313 - 14s - loss: 9.4296e-05 - val_loss: 6.3763e-05 - 14s/epoch - 11ms/step
Epoch 8/25
1313/1313 - 14s - loss: 8.1873e-05 - val_loss: 5.8109e-05 - 14s/epoch - 11ms/step
Epoch 9/25
1313/1313 - 14s - loss: 7.3564e-05 - val_loss: 5.6820e-05 - 14s/epoch - 11ms/step
Epoch 10/25
1313/1313 - 14s - loss: 6.7522e-05 - val_loss: 5.6298e-05 - 14s/epoch - 11ms/step
Epoch 11/25
1313/1313 - 14s - loss: 6.3073e-05 - val_loss: 5.7530e-05 - 14s/epoc

2023-06-16 00:11:23.190171: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:11:23.267061: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:11:23.366843: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:11:36.769740: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:11:36.799724: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 16s - loss: 2.1440e-04 - val_loss: 8.8230e-05 - 16s/epoch - 12ms/step
Epoch 2/50
1313/1313 - 14s - loss: 1.5449e-04 - val_loss: 8.3360e-05 - 14s/epoch - 11ms/step
Epoch 3/50
1313/1313 - 14s - loss: 1.4181e-04 - val_loss: 7.6530e-05 - 14s/epoch - 11ms/step
Epoch 4/50
1313/1313 - 14s - loss: 1.2625e-04 - val_loss: 6.9177e-05 - 14s/epoch - 11ms/step
Epoch 5/50
1313/1313 - 14s - loss: 1.0989e-04 - val_loss: 6.3897e-05 - 14s/epoch - 11ms/step
Epoch 6/50
1313/1313 - 14s - loss: 9.5242e-05 - val_loss: 5.8601e-05 - 14s/epoch - 11ms/step
Epoch 7/50
1313/1313 - 14s - loss: 8.2619e-05 - val_loss: 5.6270e-05 - 14s/epoch - 11ms/step
Epoch 8/50
1313/1313 - 14s - loss: 7.3110e-05 - val_loss: 5.5761e-05 - 14s/epoch - 11ms/step
Epoch 9/50
1313/1313 - 14s - loss: 6.6544e-05 - val_loss: 5.6068e-05 - 14s/epoch - 11ms/step
Epoch 10/50
1313/1313 - 14s - loss: 6.2075e-05 - val_loss: 5.8162e-05 - 14s/epoch - 11ms/step
Epoch 11/50
1313/1313 - 14s - loss: 5.9286e-05 - val_loss: 5.8775e-05 - 14s/epoc

2023-06-16 00:23:24.073993: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:23:24.154854: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:23:24.245856: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:23:37.167033: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:23:37.197139: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.9222e-04 - val_loss: 9.7331e-05 - 15s/epoch - 12ms/step
Epoch 2/50
1313/1313 - 14s - loss: 1.4589e-04 - val_loss: 8.9521e-05 - 14s/epoch - 11ms/step
Epoch 3/50
1313/1313 - 14s - loss: 1.3935e-04 - val_loss: 8.0257e-05 - 14s/epoch - 11ms/step
Epoch 4/50
1313/1313 - 14s - loss: 1.2813e-04 - val_loss: 7.1723e-05 - 14s/epoch - 11ms/step
Epoch 5/50
1313/1313 - 14s - loss: 1.1318e-04 - val_loss: 6.4609e-05 - 14s/epoch - 11ms/step
Epoch 6/50
1313/1313 - 14s - loss: 9.8568e-05 - val_loss: 5.8439e-05 - 14s/epoch - 11ms/step
Epoch 7/50
1313/1313 - 14s - loss: 8.5232e-05 - val_loss: 5.5035e-05 - 14s/epoch - 11ms/step
Epoch 8/50
1313/1313 - 14s - loss: 7.4800e-05 - val_loss: 5.4287e-05 - 14s/epoch - 11ms/step
Epoch 9/50
1313/1313 - 14s - loss: 6.7701e-05 - val_loss: 5.3411e-05 - 14s/epoch - 11ms/step
Epoch 10/50
1313/1313 - 14s - loss: 6.2895e-05 - val_loss: 5.5003e-05 - 14s/epoch - 11ms/step
Epoch 11/50
1313/1313 - 14s - loss: 5.9361e-05 - val_loss: 5.2820e-05 - 14s/epoc

2023-06-16 00:35:01.992257: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:35:02.081650: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:35:02.195927: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:35:14.663422: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:35:14.698781: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 2.3995e-04 - val_loss: 1.2439e-04 - 15s/epoch - 11ms/step
Epoch 2/50
1313/1313 - 14s - loss: 2.0508e-04 - val_loss: 1.1158e-04 - 14s/epoch - 11ms/step
Epoch 3/50
1313/1313 - 14s - loss: 1.9201e-04 - val_loss: 1.0307e-04 - 14s/epoch - 11ms/step
Epoch 4/50
1313/1313 - 14s - loss: 1.7272e-04 - val_loss: 8.9405e-05 - 14s/epoch - 11ms/step
Epoch 5/50
1313/1313 - 14s - loss: 1.5039e-04 - val_loss: 7.5622e-05 - 14s/epoch - 11ms/step
Epoch 6/50
1313/1313 - 14s - loss: 1.2731e-04 - val_loss: 6.3209e-05 - 14s/epoch - 11ms/step
Epoch 7/50
1313/1313 - 14s - loss: 1.0589e-04 - val_loss: 5.3520e-05 - 14s/epoch - 11ms/step
Epoch 8/50
1313/1313 - 14s - loss: 8.8481e-05 - val_loss: 4.5899e-05 - 14s/epoch - 11ms/step
Epoch 9/50
1313/1313 - 14s - loss: 7.5915e-05 - val_loss: 4.1589e-05 - 14s/epoch - 10ms/step
Epoch 10/50
1313/1313 - 14s - loss: 6.7456e-05 - val_loss: 4.0128e-05 - 14s/epoch - 11ms/step
Epoch 11/50
1313/1313 - 14s - loss: 6.2078e-05 - val_loss: 3.9186e-05 - 14s/epoc

2023-06-16 00:46:34.740311: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:46:34.826408: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:46:34.932756: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:46:48.218781: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 00:46:48.249317: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 16s - loss: 2.2918e-04 - val_loss: 7.9006e-05 - 16s/epoch - 12ms/step
Epoch 2/100
1313/1313 - 14s - loss: 1.6695e-04 - val_loss: 7.3483e-05 - 14s/epoch - 11ms/step
Epoch 3/100
1313/1313 - 14s - loss: 1.6555e-04 - val_loss: 6.6529e-05 - 14s/epoch - 11ms/step
Epoch 4/100
1313/1313 - 14s - loss: 1.6019e-04 - val_loss: 5.7907e-05 - 14s/epoch - 11ms/step
Epoch 5/100
1313/1313 - 14s - loss: 1.5275e-04 - val_loss: 4.9484e-05 - 14s/epoch - 11ms/step
Epoch 6/100
1313/1313 - 14s - loss: 1.4203e-04 - val_loss: 4.1391e-05 - 14s/epoch - 11ms/step
Epoch 7/100
1313/1313 - 14s - loss: 1.3024e-04 - val_loss: 3.3979e-05 - 14s/epoch - 11ms/step
Epoch 8/100
1313/1313 - 14s - loss: 1.1924e-04 - val_loss: 2.8008e-05 - 14s/epoch - 11ms/step
Epoch 9/100
1313/1313 - 14s - loss: 1.0967e-04 - val_loss: 2.3022e-05 - 14s/epoch - 11ms/step
Epoch 10/100
1313/1313 - 14s - loss: 1.0080e-04 - val_loss: 1.8854e-05 - 14s/epoch - 11ms/step
Epoch 11/100
1313/1313 - 14s - loss: 9.4408e-05 - val_loss: 1.5772e-05 

2023-06-16 01:10:22.332023: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:10:22.447535: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:10:22.601591: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:10:35.377996: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:10:35.408821: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.9100e-04 - val_loss: 9.6598e-05 - 15s/epoch - 12ms/step
Epoch 2/100
1313/1313 - 14s - loss: 1.5339e-04 - val_loss: 9.0227e-05 - 14s/epoch - 11ms/step
Epoch 3/100
1313/1313 - 14s - loss: 1.4376e-04 - val_loss: 8.1581e-05 - 14s/epoch - 11ms/step
Epoch 4/100
1313/1313 - 14s - loss: 1.2928e-04 - val_loss: 7.3897e-05 - 14s/epoch - 11ms/step
Epoch 5/100
1313/1313 - 14s - loss: 1.1527e-04 - val_loss: 6.6160e-05 - 14s/epoch - 11ms/step
Epoch 6/100
1313/1313 - 14s - loss: 1.0074e-04 - val_loss: 5.9345e-05 - 14s/epoch - 11ms/step
Epoch 7/100
1313/1313 - 14s - loss: 8.7303e-05 - val_loss: 5.4576e-05 - 14s/epoch - 11ms/step
Epoch 8/100
1313/1313 - 14s - loss: 7.6860e-05 - val_loss: 5.3011e-05 - 14s/epoch - 11ms/step
Epoch 9/100
1313/1313 - 14s - loss: 6.9648e-05 - val_loss: 5.1525e-05 - 14s/epoch - 11ms/step
Epoch 10/100
1313/1313 - 14s - loss: 6.4833e-05 - val_loss: 5.2691e-05 - 14s/epoch - 11ms/step
Epoch 11/100
1313/1313 - 14s - loss: 6.1400e-05 - val_loss: 5.2493e-05 

2023-06-16 01:33:47.047881: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:33:47.156356: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:33:47.286438: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:34:00.195451: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:34:00.225764: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 2.3194e-04 - val_loss: 1.1954e-04 - 15s/epoch - 12ms/step
Epoch 2/100
1313/1313 - 14s - loss: 1.8937e-04 - val_loss: 1.1091e-04 - 14s/epoch - 10ms/step
Epoch 3/100
1313/1313 - 14s - loss: 1.7870e-04 - val_loss: 1.0256e-04 - 14s/epoch - 10ms/step
Epoch 4/100
1313/1313 - 14s - loss: 1.6172e-04 - val_loss: 9.3257e-05 - 14s/epoch - 10ms/step
Epoch 5/100
1313/1313 - 14s - loss: 1.4134e-04 - val_loss: 8.0762e-05 - 14s/epoch - 11ms/step
Epoch 6/100
1313/1313 - 14s - loss: 1.2011e-04 - val_loss: 6.6290e-05 - 14s/epoch - 10ms/step
Epoch 7/100
1313/1313 - 14s - loss: 1.0033e-04 - val_loss: 5.7417e-05 - 14s/epoch - 11ms/step
Epoch 8/100
1313/1313 - 14s - loss: 8.4670e-05 - val_loss: 5.1290e-05 - 14s/epoch - 11ms/step
Epoch 9/100
1313/1313 - 14s - loss: 7.2924e-05 - val_loss: 4.6691e-05 - 14s/epoch - 11ms/step
Epoch 10/100
1313/1313 - 14s - loss: 6.5650e-05 - val_loss: 4.6472e-05 - 14s/epoch - 11ms/step
Epoch 11/100
1313/1313 - 14s - loss: 6.0768e-05 - val_loss: 4.8386e-05 

In [18]:
i=0
wb1 = Workbook()
ws1 = wb1.active
for m in models1:
    # make a prediction
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms1[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    i = i+1
    ws1['A'+str(i)] = 'LSTM'
    ws1['B'+str(i)] = hyperparams[i-1][0]
    ws1['C'+str(i)] = hyperparams[i-1][1]
    ws1['D'+str(i)] = hyperparams[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat))
    ws1['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat))
    ws1['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat))
    ws1['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)
    NeuralNetwork.save_model(m, 0, 'LTC',hyperparams[i-1])
    with open('LSTM_LTC'+str(hyperparams[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms1[i-1].history, f)
wb1.save('LSTM_LTC_result1_16.xlsx')

  1/164 [..............................] - ETA: 52s

2023-06-16 01:56:42.829966: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:42.901941: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 25, 50)
Epoch: 25
Neurons: 50
RMSE
2.2885726653301703
MAE
2.060700089142837
MAPE
3.7192004502137728
 11/164 [=>............................] - ETA: 0s 

2023-06-16 01:56:43.955170: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:43.994373: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 25, 60)
Epoch: 25
Neurons: 60
RMSE
0.7022373771465334
MAE
0.5275753043413614
MAPE
0.909091145119252
  9/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:44.957604: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:44.986807: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 25, 100)
Epoch: 25
Neurons: 100
RMSE
2.512660075673723
MAE
2.2688047190970675
MAPE
4.096600471134123
 10/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:46.038486: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:46.064366: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 50, 50)
Epoch: 50
Neurons: 50
RMSE
0.7793709984258018
MAE
0.6080133938616138
MAPE
1.0747212187992226
 10/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:47.025181: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:47.051284: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 50, 60)
Epoch: 50
Neurons: 60
RMSE
1.6573402795015688
MAE
1.4911055439352776
MAPE
2.6693485220478723
 10/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:48.015043: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:48.042391: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 50, 100)
Epoch: 50
Neurons: 100
RMSE
1.5297136661952473
MAE
1.3640298497799959
MAPE
2.444679185113684
 10/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:49.094141: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:49.120465: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 100, 50)
Epoch: 100
Neurons: 50
RMSE
1.104580612187744
MAE
0.9010222039596532
MAPE
1.6321118899662603
 10/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:50.078193: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:50.104857: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 100, 60)
Epoch: 100
Neurons: 60
RMSE
1.6755515800780376
MAE
1.4840962479483788
MAPE
2.675413094457661
 10/164 [>.............................] - ETA: 0s 

2023-06-16 01:56:51.121869: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 01:56:51.147920: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 100, 100)
Epoch: 100
Neurons: 100
RMSE
0.6594285874029607
MAE
0.48332780897093025
MAPE
0.8420274888076735


In [19]:
test_X

array([[[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
        [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        ...,
        [0.09558231, 0.08501719, 0.09767687, 0.00433742, 0.09453978],
        [0.09454224, 0.0871003 , 0.09846885, 0.00441158, 0.0973999 ],
        [0.09714241, 0.08683991, 0.09846885, 0.0045675 , 0.09453978]],

       [[0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        ...,
        [0.09454224, 0.0871003 , 0.09846885, 0.00441158, 0.0973999 ],
        [0.09714241, 0.08683991, 0.09846885, 0.0045675 , 0.09453978],
        [0.09454224, 0.08501719, 0.09846885, 0.00252454, 0.09479979]],

       [[0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.0