In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import NeuralNetwork
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
btc_dfd = pd.read_csv('../Dataset/Binance_BTCUSDT_1h.csv')
btc_dfd

Date      Open      High       Low     Close  \
0      2022-12-31 23:00:00  16520.28  16551.24  16487.74  16542.40   
1      2022-12-31 22:00:00  16548.28  16567.49  16470.00  16520.81   
2      2022-12-31 21:00:00  16568.19  16571.64  16544.12  16548.28   
3      2022-12-31 20:00:00  16570.14  16574.97  16564.09  16568.60   
4      2022-12-31 19:00:00  16577.78  16590.06  16565.10  16570.14   
...                    ...       ...       ...       ...       ...   
26269  2020-01-01 04:00:00   7225.00   7230.00   7215.03   7217.27   
26270  2020-01-01 03:00:00   7242.66   7245.00   7220.00   7225.01   
26271  2020-01-01 02:00:00   7215.52   7244.87   7211.41   7242.85   
26272  2020-01-01 01:00:00   7176.47   7230.00   7175.71   7216.27   
26273  2020-01-01 00:00:00   7195.24   7196.25   7175.46   7177.02   

        Volume USDT  
0      8.217183e+07  
1      1.106669e+08  
2      5.992803e+07  
3      4.344849e+07  
4      6.704605e+07  
...             ...  
26269  3.379094e+06  
26270  5.667367e+06  
26271  4.736719e+06  
26272  6.365953e+06  
26273  3.675857e+06  

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(btc_dfd)
df

Date      Open      High       Low     Close  \
0      2020-01-01 00:00:00   7195.24   7196.25   7175.46   7177.02   
1      2020-01-01 01:00:00   7176.47   7230.00   7175.71   7216.27   
2      2020-01-01 02:00:00   7215.52   7244.87   7211.41   7242.85   
3      2020-01-01 03:00:00   7242.66   7245.00   7220.00   7225.01   
4      2020-01-01 04:00:00   7225.00   7230.00   7215.03   7217.27   
...                    ...       ...       ...       ...       ...   
26269  2022-12-31 19:00:00  16577.78  16590.06  16565.10  16570.14   
26270  2022-12-31 20:00:00  16570.14  16574.97  16564.09  16568.60   
26271  2022-12-31 21:00:00  16568.19  16571.64  16544.12  16548.28   
26272  2022-12-31 22:00:00  16548.28  16567.49  16470.00  16520.81   
26273  2022-12-31 23:00:00  16520.28  16551.24  16487.74  16542.40   

        Volume USDT  
0      3.675857e+06  
1      6.365953e+06  
2      4.736719e+06  
3      5.667367e+06  
4      3.379094e+06  
...             ...  
26269  6.704605e+07  
26270  4.344849e+07  
26271  5.992803e+07  
26272  1.106669e+08  
26273  8.217183e+07  

[26274 rows x 6 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.39451404, 0.38918512, 0.39751838, 0.01247029, 0.39344233],
       [0.39342821, 0.38742771, 0.39264325, 0.02946575, 0.3886748 ],
       [0.38866059, 0.38484765, 0.39034385, 0.03564371, 0.38670838]])

In [6]:
test

array([[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
       [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
       [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [7]:
train.shape

(21019, 5)

In [8]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [9]:
train_X

array([[[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
        [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        ...,
        [0.04809152, 0.04075928, 0.05263522, 0.00184419, 0.04755357],
        [0.04753806, 0.0402884 , 0.05246744, 0.00194012, 0.0475979 ],
        [0.0475869 , 0.04041777, 0.05262687, 0.00093754, 0.04775557]],

       [[0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.04797246],
        ...,
        [0.04753806, 0.0402884 , 0.05246744, 0.00194012, 0.0475979 ],
        [0.0475869 , 0.04041777, 0.05262687, 0.00093754, 0.04775557],
        [0.04774611, 0.04039696, 0.05262145, 0.00096387, 0.04744504]],

       [[0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.0

In [10]:
train_y

array([0.04744504, 0.04710444, 0.04649346, ..., 0.39344233, 0.3886748 ,
       0.38670838])

In [11]:
test_X

array([[[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
        [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        ...,
        [0.38279443, 0.37655397, 0.38229271, 0.02962508, 0.37981398],
        [0.37980004, 0.37607455, 0.38312154, 0.0179209 , 0.38255028],
        [0.38253615, 0.37634617, 0.38144779, 0.05495828, 0.37959724]],

       [[0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        ...,
        [0.37980004, 0.37607455, 0.38312154, 0.0179209 , 0.38255028],
        [0.38253615, 0.37634617, 0.38144779, 0.05495828, 0.37959724],
        [0.37958331, 0.37479453, 0.38374301, 0.01228897, 0.38068448]],

       [[0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.3

In [12]:
test_y

array([0.38068448, 0.38275027, 0.38296623, ..., 0.19251245, 0.19208658,
       0.19242129])

In [13]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 5) (20994,) (5230, 25, 5) (5230,)


In [14]:
train_X.shape[1]

25

In [15]:
train_X.shape[2]

5

## Model Training

In [16]:
hyperparams = []
batch = [16]
epoch = [25, 50, 100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(16, 25, 50),
 (16, 25, 60),
 (16, 25, 100),
 (16, 50, 50),
 (16, 50, 60),
 (16, 50, 100),
 (16, 100, 50),
 (16, 100, 60),
 (16, 100, 100)]

In [19]:
lstms1 = []
models1 = []
for batch, epoch, neuron in hyperparams:
    model, lstm = NeuralNetwork.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms1.append(lstm)
    models1.append(model)

Metal device set to: Apple M1


2023-06-14 17:46:44.904524: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-06-14 17:46:44.905481: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/25


2023-06-14 17:46:45.300868: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-06-14 17:46:45.706926: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:46:45.801473: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:46:45.951626: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:46:58.432712: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:46:58.462366: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.8342e-04 - val_loss: 0.0013 - 15s/epoch - 11ms/step
Epoch 2/25
1313/1313 - 14s - loss: 1.5149e-04 - val_loss: 0.0012 - 14s/epoch - 11ms/step
Epoch 3/25
1313/1313 - 14s - loss: 1.8506e-04 - val_loss: 0.0018 - 14s/epoch - 11ms/step
Epoch 4/25
1313/1313 - 14s - loss: 2.0412e-04 - val_loss: 0.0015 - 14s/epoch - 11ms/step
Epoch 5/25
1313/1313 - 14s - loss: 1.8545e-04 - val_loss: 0.0011 - 14s/epoch - 11ms/step
Epoch 6/25
1313/1313 - 14s - loss: 1.6585e-04 - val_loss: 8.6879e-04 - 14s/epoch - 11ms/step
Epoch 7/25
1313/1313 - 14s - loss: 1.5553e-04 - val_loss: 7.2280e-04 - 14s/epoch - 11ms/step
Epoch 8/25
1313/1313 - 14s - loss: 1.5063e-04 - val_loss: 6.0576e-04 - 14s/epoch - 11ms/step
Epoch 9/25
1313/1313 - 14s - loss: 1.4840e-04 - val_loss: 5.5783e-04 - 14s/epoch - 11ms/step
Epoch 10/25
1313/1313 - 14s - loss: 1.5276e-04 - val_loss: 5.1748e-04 - 14s/epoch - 11ms/step
Epoch 11/25
1313/1313 - 14s - loss: 1.6197e-04 - val_loss: 4.8607e-04 - 14s/epoch - 11ms/step
Epoch 

2023-06-14 17:52:35.408532: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:52:35.488773: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:52:35.576038: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:52:48.182689: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:52:48.212604: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.7488e-04 - val_loss: 0.0012 - 15s/epoch - 11ms/step
Epoch 2/25
1313/1313 - 14s - loss: 1.5209e-04 - val_loss: 0.0010 - 14s/epoch - 11ms/step
Epoch 3/25
1313/1313 - 14s - loss: 1.9751e-04 - val_loss: 0.0018 - 14s/epoch - 11ms/step
Epoch 4/25
1313/1313 - 14s - loss: 2.4206e-04 - val_loss: 0.0016 - 14s/epoch - 11ms/step
Epoch 5/25
1313/1313 - 14s - loss: 2.2620e-04 - val_loss: 0.0013 - 14s/epoch - 11ms/step
Epoch 6/25
1313/1313 - 14s - loss: 2.3002e-04 - val_loss: 0.0011 - 14s/epoch - 11ms/step
Epoch 7/25
1313/1313 - 14s - loss: 2.5582e-04 - val_loss: 8.5211e-04 - 14s/epoch - 11ms/step
Epoch 8/25
1313/1313 - 14s - loss: 2.8823e-04 - val_loss: 7.0427e-04 - 14s/epoch - 11ms/step
Epoch 9/25
1313/1313 - 14s - loss: 3.2772e-04 - val_loss: 6.2139e-04 - 14s/epoch - 11ms/step
Epoch 10/25
1313/1313 - 14s - loss: 4.1448e-04 - val_loss: 5.0483e-04 - 14s/epoch - 11ms/step
Epoch 11/25
1313/1313 - 14s - loss: 5.1012e-04 - val_loss: 2.9949e-04 - 14s/epoch - 10ms/step
Epoch 12/2

2023-06-14 17:58:19.711014: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:58:19.805877: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:58:19.899913: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:58:32.341307: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 17:58:32.371425: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.7162e-04 - val_loss: 0.0018 - 15s/epoch - 11ms/step
Epoch 2/25
1313/1313 - 14s - loss: 1.4811e-04 - val_loss: 0.0011 - 14s/epoch - 10ms/step
Epoch 3/25
1313/1313 - 14s - loss: 1.4312e-04 - val_loss: 0.0014 - 14s/epoch - 10ms/step
Epoch 4/25
1313/1313 - 14s - loss: 1.6471e-04 - val_loss: 0.0018 - 14s/epoch - 10ms/step
Epoch 5/25
1313/1313 - 14s - loss: 2.0241e-04 - val_loss: 0.0019 - 14s/epoch - 10ms/step
Epoch 6/25
1313/1313 - 14s - loss: 2.1288e-04 - val_loss: 0.0014 - 14s/epoch - 10ms/step
Epoch 7/25
1313/1313 - 14s - loss: 1.9787e-04 - val_loss: 0.0011 - 14s/epoch - 10ms/step
Epoch 8/25
1313/1313 - 14s - loss: 2.0085e-04 - val_loss: 8.9544e-04 - 14s/epoch - 10ms/step
Epoch 9/25
1313/1313 - 14s - loss: 2.2889e-04 - val_loss: 8.1902e-04 - 14s/epoch - 10ms/step
Epoch 10/25
1313/1313 - 14s - loss: 2.8331e-04 - val_loss: 8.0263e-04 - 14s/epoch - 10ms/step
Epoch 11/25
1313/1313 - 14s - loss: 3.5535e-04 - val_loss: 7.6827e-04 - 14s/epoch - 10ms/step
Epoch 12/25
13

2023-06-14 18:04:03.201723: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:04:03.278910: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:04:03.373176: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:04:16.407254: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:04:16.437565: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.7875e-04 - val_loss: 0.0011 - 15s/epoch - 12ms/step
Epoch 2/50
1313/1313 - 14s - loss: 1.6642e-04 - val_loss: 0.0015 - 14s/epoch - 11ms/step
Epoch 3/50
1313/1313 - 14s - loss: 2.1529e-04 - val_loss: 0.0018 - 14s/epoch - 11ms/step
Epoch 4/50
1313/1313 - 14s - loss: 2.0209e-04 - val_loss: 0.0014 - 14s/epoch - 11ms/step
Epoch 5/50
1313/1313 - 14s - loss: 1.8206e-04 - val_loss: 0.0011 - 14s/epoch - 11ms/step
Epoch 6/50
1313/1313 - 14s - loss: 1.6652e-04 - val_loss: 8.5448e-04 - 14s/epoch - 11ms/step
Epoch 7/50
1313/1313 - 14s - loss: 1.6417e-04 - val_loss: 7.4487e-04 - 14s/epoch - 11ms/step
Epoch 8/50
1313/1313 - 14s - loss: 1.6945e-04 - val_loss: 6.7953e-04 - 14s/epoch - 11ms/step
Epoch 9/50
1313/1313 - 14s - loss: 1.8811e-04 - val_loss: 6.1037e-04 - 14s/epoch - 11ms/step
Epoch 10/50
1313/1313 - 14s - loss: 2.1272e-04 - val_loss: 5.3427e-04 - 14s/epoch - 11ms/step
Epoch 11/50
1313/1313 - 14s - loss: 2.4258e-04 - val_loss: 4.6931e-04 - 14s/epoch - 11ms/step
Epoch 

2023-06-14 18:15:58.029305: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:15:58.112776: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:15:58.205851: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:16:10.916740: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:16:10.946881: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.6314e-04 - val_loss: 0.0011 - 15s/epoch - 11ms/step
Epoch 2/50
1313/1313 - 14s - loss: 1.7001e-04 - val_loss: 0.0016 - 14s/epoch - 11ms/step
Epoch 3/50
1313/1313 - 14s - loss: 2.5469e-04 - val_loss: 0.0021 - 14s/epoch - 11ms/step
Epoch 4/50
1313/1313 - 14s - loss: 2.6267e-04 - val_loss: 0.0016 - 14s/epoch - 11ms/step
Epoch 5/50
1313/1313 - 14s - loss: 2.6559e-04 - val_loss: 0.0013 - 14s/epoch - 11ms/step
Epoch 6/50
1313/1313 - 14s - loss: 2.9852e-04 - val_loss: 0.0010 - 14s/epoch - 11ms/step
Epoch 7/50
1313/1313 - 14s - loss: 3.3761e-04 - val_loss: 8.6335e-04 - 14s/epoch - 11ms/step
Epoch 8/50
1313/1313 - 14s - loss: 4.0290e-04 - val_loss: 7.0382e-04 - 14s/epoch - 11ms/step
Epoch 9/50
1313/1313 - 14s - loss: 4.9450e-04 - val_loss: 4.7440e-04 - 14s/epoch - 11ms/step
Epoch 10/50
1313/1313 - 14s - loss: 5.7033e-04 - val_loss: 2.6392e-04 - 14s/epoch - 11ms/step
Epoch 11/50
1313/1313 - 14s - loss: 6.3177e-04 - val_loss: 1.1843e-04 - 14s/epoch - 11ms/step
Epoch 12/5

2023-06-14 18:27:40.561338: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:27:40.640763: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:27:40.741442: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:27:53.164946: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:27:53.195094: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.7678e-04 - val_loss: 0.0018 - 15s/epoch - 11ms/step
Epoch 2/50
1313/1313 - 14s - loss: 1.7221e-04 - val_loss: 0.0015 - 14s/epoch - 10ms/step
Epoch 3/50
1313/1313 - 14s - loss: 1.8063e-04 - val_loss: 0.0020 - 14s/epoch - 10ms/step
Epoch 4/50
1313/1313 - 14s - loss: 2.1650e-04 - val_loss: 0.0021 - 14s/epoch - 10ms/step
Epoch 5/50
1313/1313 - 14s - loss: 2.1365e-04 - val_loss: 0.0015 - 14s/epoch - 10ms/step
Epoch 6/50
1313/1313 - 14s - loss: 1.8688e-04 - val_loss: 0.0011 - 14s/epoch - 10ms/step
Epoch 7/50
1313/1313 - 14s - loss: 1.6966e-04 - val_loss: 8.6841e-04 - 14s/epoch - 10ms/step
Epoch 8/50
1313/1313 - 14s - loss: 1.6454e-04 - val_loss: 7.3609e-04 - 14s/epoch - 10ms/step
Epoch 9/50
1313/1313 - 14s - loss: 1.6675e-04 - val_loss: 6.7948e-04 - 14s/epoch - 10ms/step
Epoch 10/50
1313/1313 - 14s - loss: 1.7746e-04 - val_loss: 6.5325e-04 - 14s/epoch - 10ms/step
Epoch 11/50
1313/1313 - 14s - loss: 1.9477e-04 - val_loss: 6.0823e-04 - 14s/epoch - 10ms/step
Epoch 12/5

2023-06-14 18:39:09.327822: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:39:09.410961: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:39:09.513945: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:39:22.507090: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 18:39:22.537574: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 16s - loss: 1.8822e-04 - val_loss: 0.0011 - 16s/epoch - 12ms/step
Epoch 2/100
1313/1313 - 14s - loss: 1.9087e-04 - val_loss: 0.0017 - 14s/epoch - 11ms/step
Epoch 3/100
1313/1313 - 14s - loss: 2.4156e-04 - val_loss: 0.0016 - 14s/epoch - 11ms/step
Epoch 4/100
1313/1313 - 14s - loss: 2.2445e-04 - val_loss: 0.0013 - 14s/epoch - 11ms/step
Epoch 5/100
1313/1313 - 14s - loss: 2.1289e-04 - val_loss: 0.0010 - 14s/epoch - 11ms/step
Epoch 6/100
1313/1313 - 14s - loss: 2.1313e-04 - val_loss: 8.6773e-04 - 14s/epoch - 11ms/step
Epoch 7/100
1313/1313 - 14s - loss: 2.2558e-04 - val_loss: 7.1682e-04 - 14s/epoch - 11ms/step
Epoch 8/100
1313/1313 - 14s - loss: 2.4617e-04 - val_loss: 6.2174e-04 - 14s/epoch - 11ms/step
Epoch 9/100
1313/1313 - 14s - loss: 2.6727e-04 - val_loss: 5.7629e-04 - 14s/epoch - 11ms/step
Epoch 10/100
1313/1313 - 14s - loss: 3.0459e-04 - val_loss: 5.3255e-04 - 14s/epoch - 11ms/step
Epoch 11/100
1313/1313 - 14s - loss: 3.7320e-04 - val_loss: 4.7215e-04 - 14s/epoch - 11ms/s

2023-06-14 19:02:49.540062: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:02:49.625105: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:02:49.741181: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:03:02.468162: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:03:02.498369: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.5722e-04 - val_loss: 0.0011 - 15s/epoch - 11ms/step
Epoch 2/100
1313/1313 - 14s - loss: 1.5220e-04 - val_loss: 0.0013 - 14s/epoch - 11ms/step
Epoch 3/100
1313/1313 - 14s - loss: 2.2208e-04 - val_loss: 0.0020 - 14s/epoch - 11ms/step
Epoch 4/100
1313/1313 - 14s - loss: 2.4402e-04 - val_loss: 0.0016 - 14s/epoch - 11ms/step
Epoch 5/100
1313/1313 - 14s - loss: 2.3522e-04 - val_loss: 0.0013 - 14s/epoch - 11ms/step
Epoch 6/100
1313/1313 - 14s - loss: 2.4766e-04 - val_loss: 0.0010 - 14s/epoch - 11ms/step
Epoch 7/100
1313/1313 - 14s - loss: 2.7941e-04 - val_loss: 8.3877e-04 - 14s/epoch - 11ms/step
Epoch 8/100
1313/1313 - 14s - loss: 3.2692e-04 - val_loss: 7.4322e-04 - 14s/epoch - 11ms/step
Epoch 9/100
1313/1313 - 14s - loss: 4.1064e-04 - val_loss: 6.3516e-04 - 14s/epoch - 11ms/step
Epoch 10/100
1313/1313 - 14s - loss: 5.2966e-04 - val_loss: 4.2678e-04 - 14s/epoch - 11ms/step
Epoch 11/100
1313/1313 - 14s - loss: 6.3472e-04 - val_loss: 2.0789e-04 - 14s/epoch - 11ms/step


2023-06-14 19:26:06.312278: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:26:06.429937: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:26:06.557534: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:26:19.230089: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:26:19.260352: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 15s - loss: 1.7665e-04 - val_loss: 0.0018 - 15s/epoch - 11ms/step
Epoch 2/100
1313/1313 - 14s - loss: 1.6745e-04 - val_loss: 0.0014 - 14s/epoch - 10ms/step
Epoch 3/100
1313/1313 - 14s - loss: 1.6431e-04 - val_loss: 0.0018 - 14s/epoch - 10ms/step
Epoch 4/100
1313/1313 - 14s - loss: 1.9640e-04 - val_loss: 0.0021 - 14s/epoch - 10ms/step
Epoch 5/100
1313/1313 - 14s - loss: 2.1236e-04 - val_loss: 0.0017 - 14s/epoch - 10ms/step
Epoch 6/100
1313/1313 - 14s - loss: 1.8552e-04 - val_loss: 0.0012 - 14s/epoch - 10ms/step
Epoch 7/100
1313/1313 - 14s - loss: 1.6488e-04 - val_loss: 9.0458e-04 - 14s/epoch - 10ms/step
Epoch 8/100
1313/1313 - 14s - loss: 1.5374e-04 - val_loss: 7.2741e-04 - 14s/epoch - 10ms/step
Epoch 9/100
1313/1313 - 14s - loss: 1.5031e-04 - val_loss: 6.3890e-04 - 14s/epoch - 10ms/step
Epoch 10/100
1313/1313 - 14s - loss: 1.5434e-04 - val_loss: 6.0571e-04 - 14s/epoch - 10ms/step
Epoch 11/100
1313/1313 - 14s - loss: 1.6163e-04 - val_loss: 5.6481e-04 - 14s/epoch - 10ms/step


In [21]:
i=0
wb1 = Workbook()
ws1 = wb1.active
for m in models1:
    # make a prediction
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms1[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    i = i+1
    ws1['A'+str(i)] = 'LSTM'
    ws1['B'+str(i)] = hyperparams[i-1][0]
    ws1['C'+str(i)] = hyperparams[i-1][1]
    ws1['D'+str(i)] = hyperparams[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat))
    ws1['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat))
    ws1['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat))
    ws1['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)
    NeuralNetwork.save_model(m, 0, 'BTC',hyperparams[i-1])
    with open('LSTM_BTC'+str(hyperparams[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms1[i-1].history, f)
wb1.save('LSTM_BTC_result1_16.xlsx')

164/164 [==============================] - 1s 4ms/step
(16, 25, 50)
Epoch: 25
Neurons: 50
RMSE
513.631109731846
MAE
441.37227894956965
MAPE
2.291858858486409
 10/164 [>.............................] - ETA: 0s 

2023-06-14 19:57:54.831092: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:57:54.899003: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 25, 60)
Epoch: 25
Neurons: 60
RMSE
222.42560215946438
MAE
167.5786969706017
MAPE
0.8304550848228058
  8/164 [>.............................] - ETA: 1s 

2023-06-14 19:57:55.873800: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:57:55.902237: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 25, 100)
Epoch: 25
Neurons: 100
RMSE
269.1846919945757
MAE
208.2610190382997
MAPE
1.052033486201714
 23/164 [===>..........................] - ETA: 0s

2023-06-14 19:57:56.977482: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:57:57.002966: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 50, 50)
Epoch: 50
Neurons: 50
RMSE
240.14692516786636
MAE
153.26418003107068
MAPE
0.7506943339598187
 20/164 [==>...........................] - ETA: 0s

2023-06-14 19:57:57.950231: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:57:57.976621: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(16, 50, 60)
Epoch: 50
Neurons: 60
RMSE
277.42094319771314
MAE
219.05383644538762
MAPE
1.1285141943549448
  9/164 [>.............................] - ETA: 1s 

2023-06-14 19:57:58.946235: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:57:58.972570: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 50, 100)
Epoch: 50
Neurons: 100
RMSE
308.4263245529265
MAE
207.6547781952083
MAPE
1.0460151417002983
 10/164 [>.............................] - ETA: 0s 

2023-06-14 19:58:00.066362: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:58:00.093465: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 100, 50)
Epoch: 100
Neurons: 50
RMSE
314.026398877717
MAE
280.63618791079153
MAPE
1.4077950175333402
 22/164 [===>..........................] - ETA: 0s

2023-06-14 19:58:01.110862: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:58:01.137287: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 100, 60)
Epoch: 100
Neurons: 60
RMSE
467.1001844389783
MAE
432.3491084861976
MAPE
2.235332220168606
  9/164 [>.............................] - ETA: 0s 

2023-06-14 19:58:02.113511: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-14 19:58:02.139655: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(16, 100, 100)
Epoch: 100
Neurons: 100
RMSE
328.2659375521623
MAE
191.9607528904759
MAPE
0.9614785110560791


In [ ]:
test_X