In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
eth_dfd = pd.read_csv('../Dataset/Binance_ETHUSDT_1h.csv')
eth_dfd

Unix                 Date   Symbol     Open     High      Low  \
0      1672527600000  2022-12-31 23:00:00  ETHUSDT  1196.18  1197.43  1193.60   
1      1672524000000  2022-12-31 22:00:00  ETHUSDT  1200.09  1201.11  1193.08   
2      1672520400000  2022-12-31 21:00:00  ETHUSDT  1202.33  1203.00  1199.83   
3      1672516800000  2022-12-31 20:00:00  ETHUSDT  1202.66  1203.71  1202.30   
4      1672513200000  2022-12-31 19:00:00  ETHUSDT  1199.59  1205.61  1199.42   
...              ...                  ...      ...      ...      ...      ...   
26269  1577851200000  2020-01-01 04:00:00  ETHUSDT   130.21   130.74   130.15   
26270  1577847600000  2020-01-01 03:00:00  ETHUSDT   130.85   130.89   129.94   
26271  1577844000000  2020-01-01 02:00:00  ETHUSDT   130.63   130.98   130.35   
26272  1577840400000  2020-01-01 01:00:00  ETHUSDT   128.87   130.65   128.78   
26273  1577836800000  2020-01-01 00:00:00  ETHUSDT   129.16   129.19   128.68   

         Close   Volume ETH   Volume USDT  tradecount  
0      1196.13   5927.43200  7.086714e+06       11029  
1      1196.19   9549.47930  1.143952e+07       13241  
2      1200.10   3865.48620  4.643401e+06        7913  
3      1202.34   3557.34730  4.278879e+06        7917  
4      1202.65   6435.02040  7.738029e+06        9906  
...        ...          ...           ...         ...  
26269   130.20   3397.90747  4.430067e+05        2264  
26270   130.20   4968.55433  6.473610e+05        2818  
26271   130.85   7603.35623  9.940256e+05        3046  
26272   130.64  11344.65516  1.474278e+06        4885  
26273   128.87   7769.17336  1.000930e+06        2504  

[26274 rows x 10 columns]

In [3]:
df_no_dup = Preprocessing.handle_duplicate(eth_dfd)
df_no_dup

duplicate ok


Unix                 Date   Symbol     Open     High      Low  \
0      1672527600000  2022-12-31 23:00:00  ETHUSDT  1196.18  1197.43  1193.60   
1      1672524000000  2022-12-31 22:00:00  ETHUSDT  1200.09  1201.11  1193.08   
2      1672520400000  2022-12-31 21:00:00  ETHUSDT  1202.33  1203.00  1199.83   
3      1672516800000  2022-12-31 20:00:00  ETHUSDT  1202.66  1203.71  1202.30   
4      1672513200000  2022-12-31 19:00:00  ETHUSDT  1199.59  1205.61  1199.42   
...              ...                  ...      ...      ...      ...      ...   
26269  1577851200000  2020-01-01 04:00:00  ETHUSDT   130.21   130.74   130.15   
26270  1577847600000  2020-01-01 03:00:00  ETHUSDT   130.85   130.89   129.94   
26271  1577844000000  2020-01-01 02:00:00  ETHUSDT   130.63   130.98   130.35   
26272  1577840400000  2020-01-01 01:00:00  ETHUSDT   128.87   130.65   128.78   
26273  1577836800000  2020-01-01 00:00:00  ETHUSDT   129.16   129.19   128.68   

         Close   Volume ETH   Volume USDT  tradecount  
0      1196.13   5927.43200  7.086714e+06       11029  
1      1196.19   9549.47930  1.143952e+07       13241  
2      1200.10   3865.48620  4.643401e+06        7913  
3      1202.34   3557.34730  4.278879e+06        7917  
4      1202.65   6435.02040  7.738029e+06        9906  
...        ...          ...           ...         ...  
26269   130.20   3397.90747  4.430067e+05        2264  
26270   130.20   4968.55433  6.473610e+05        2818  
26271   130.85   7603.35623  9.940256e+05        3046  
26272   130.64  11344.65516  1.474278e+06        4885  
26273   128.87   7769.17336  1.000930e+06        2504  

[26274 rows x 10 columns]

In [4]:
df = Preprocessing.feature_selection(df_no_dup)
df

Close
0       128.87
1       130.64
2       130.85
3       130.20
4       130.20
...        ...
26269  1202.65
26270  1202.34
26271  1200.10
26272  1196.19
26273  1196.13

[26274 rows x 1 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df)
miss

No missing value


Close
0       128.87
1       130.64
2       130.85
3       130.20
4       130.20
...        ...
26269  1202.65
26270  1202.34
26271  1200.10
26272  1196.19
26273  1196.13

[26274 rows x 1 columns]

In [6]:
x, scaler = Preprocessing.minmax_scale(miss)
x

array([[0.00678935],
       [0.00716197],
       [0.00720618],
       ...,
       [0.23230718],
       [0.23148404],
       [0.2314714 ]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.00678935],
       [0.00716197],
       [0.00720618],
       ...,
       [0.36294049],
       [0.35696376],
       [0.35310278]])

In [8]:
test

array([[0.34664396],
       [0.34877655],
       [0.35186281],
       ...,
       [0.23230718],
       [0.23148404],
       [0.2314714 ]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,50)
test_X, test_y = Preprocessing.create_dataset(test,50)

In [10]:
train_X

array([[[0.00678935],
        [0.00716197],
        [0.00720618],
        ...,
        [0.00643567],
        [0.0064104 ],
        [0.00619357]],

       [[0.00716197],
        [0.00720618],
        [0.00706934],
        ...,
        [0.0064104 ],
        [0.00619357],
        [0.00637883]],

       [[0.00720618],
        [0.00706934],
        [0.00706934],
        ...,
        [0.00619357],
        [0.00637883],
        [0.00637251]],

       ...,

       [[0.39445358],
        [0.3972451 ],
        [0.39709984],
        ...,
        [0.36419099],
        [0.36438046],
        [0.36570254]],

       [[0.3972451 ],
        [0.39709984],
        [0.39636933],
        ...,
        [0.36438046],
        [0.36570254],
        [0.36294049]],

       [[0.39709984],
        [0.39636933],
        [0.3954304 ],
        ...,
        [0.36570254],
        [0.36294049],
        [0.35696376]]])

In [11]:
train_y

array([0.00637883, 0.00637251, 0.00687987, ..., 0.36294049, 0.35696376,
       0.35310278])

In [12]:
test_X

array([[[0.34664396],
        [0.34877655],
        [0.35186281],
        ...,
        [0.35642272],
        [0.35359541],
        [0.3519828 ]],

       [[0.34877655],
        [0.35186281],
        [0.34708184],
        ...,
        [0.35359541],
        [0.3519828 ],
        [0.35364383]],

       [[0.35186281],
        [0.34708184],
        [0.34520188],
        ...,
        [0.3519828 ],
        [0.35364383],
        [0.3533912 ]],

       ...,

       [[0.23195771],
        [0.23152403],
        [0.23125457],
        ...,
        [0.23220192],
        [0.23284401],
        [0.23277875]],

       [[0.23152403],
        [0.23125457],
        [0.23182508],
        ...,
        [0.23284401],
        [0.23277875],
        [0.23230718]],

       [[0.23125457],
        [0.23182508],
        [0.23238928],
        ...,
        [0.23277875],
        [0.23230718],
        [0.23148404]]])

In [13]:
test_y

array([0.35364383, 0.3533912 , 0.35539537, ..., 0.23230718, 0.23148404,
       0.2314714 ])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20969, 50, 1) (20969,) (5205, 50, 1) (5205,)


## Model Training

In [15]:
hyperparam = [(32,100,100)]

In [16]:
for batch, epoch, neuron in hyperparam:
    model1, bilstm1 = LSTMUnit.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)

Metal device set to: Apple M1
Epoch 1/100


2023-04-07 20:33:39.426622: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-07 20:33:39.426748: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-04-07 20:33:39.564759: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-04-07 20:33:41.087849: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 20:33:41.352598: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 20:33:41.370232: I tensorflow/core/grappler/o

656/656 - 44s - loss: 7.0701e-04 - val_loss: 0.0020 - 44s/epoch - 67ms/step
Epoch 2/100
656/656 - 43s - loss: 9.8903e-04 - val_loss: 0.0023 - 43s/epoch - 65ms/step
Epoch 3/100
656/656 - 45s - loss: 0.0012 - val_loss: 0.0032 - 45s/epoch - 69ms/step
Epoch 4/100
656/656 - 46s - loss: 0.0013 - val_loss: 0.0040 - 46s/epoch - 71ms/step
Epoch 5/100
656/656 - 47s - loss: 0.0013 - val_loss: 0.0039 - 47s/epoch - 72ms/step
Epoch 6/100
656/656 - 48s - loss: 0.0012 - val_loss: 0.0035 - 48s/epoch - 73ms/step
Epoch 7/100
656/656 - 48s - loss: 0.0011 - val_loss: 0.0029 - 48s/epoch - 73ms/step
Epoch 8/100
656/656 - 48s - loss: 9.9316e-04 - val_loss: 0.0023 - 48s/epoch - 74ms/step
Epoch 9/100
656/656 - 48s - loss: 8.3591e-04 - val_loss: 0.0017 - 48s/epoch - 74ms/step
Epoch 10/100
656/656 - 48s - loss: 6.5493e-04 - val_loss: 0.0011 - 48s/epoch - 74ms/step
Epoch 11/100
656/656 - 48s - loss: 5.1058e-04 - val_loss: 7.2420e-04 - 48s/epoch - 73ms/step
Epoch 12/100
656/656 - 49s - loss: 4.1406e-04 - val_loss: 

In [19]:
i=0
# make a prediction
test_x2 = test_X
yhat = LSTMUnit.predict(test_x2, model1)
inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
print(hyperparam[i])
print("Epoch: "+ str(bilstm1.params['epochs']))
print("Neurons: "+str(model1.layers[0].layer.units))
i = i+1
print('RMSE')
print(Evaluation.rmse(inv_y,inv_yhat))
print('MAE')
print(Evaluation.mae(inv_y,inv_yhat))
print('MAPE')
print(Evaluation.mape(inv_y,inv_yhat))
LSTMUnit.save_model(model1, 1, 'ETH',hyperparam[0])
with open('BiLSTM_ETH'+str(hyperparam[0])+'.pkl', 'wb') as f:
    pickle.dump(bilstm1.history, f)

163/163 [==============================] - 3s 15ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
RMSE
24.667426324898152
MAE
21.990609811685776
MAPE
1.630070811419378
