In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
ltc_dfd = pd.read_csv('../Dataset/Binance_LTCUSDT_1h.csv')
ltc_dfd

Date   Open   High    Low  Close   Volume USDT
0      2022-12-31 23:00:00  70.08  70.30  69.79  70.14  9.486568e+05
1      2022-12-31 22:00:00  70.24  70.24  69.71  70.09  8.838422e+05
2      2022-12-31 21:00:00  70.40  70.45  70.19  70.23  6.820723e+05
3      2022-12-31 20:00:00  70.15  70.53  70.08  70.39  1.173164e+06
4      2022-12-31 19:00:00  69.93  70.32  69.93  70.15  9.964355e+05
...                    ...    ...    ...    ...    ...           ...
26269  2020-01-01 04:00:00  41.53  41.85  41.45  41.59  2.214516e+05
26270  2020-01-01 03:00:00  41.84  41.85  41.49  41.53  1.613043e+05
26271  2020-01-01 02:00:00  41.63  41.88  41.62  41.85  2.402871e+05
26272  2020-01-01 01:00:00  41.28  41.70  41.27  41.62  2.830715e+05
26273  2020-01-01 00:00:00  41.29  41.29  41.16  41.28  1.165827e+05

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(ltc_dfd)
df

Close
0      41.28
1      41.62
2      41.85
3      41.53
4      41.59
...      ...
26269  70.15
26270  70.39
26271  70.23
26272  70.09
26273  70.14

[26274 rows x 1 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.04170567],
       [0.0425897 ],
       [0.04318773],
       ...,
       [0.11697868],
       [0.11661466],
       [0.11674467]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04170567],
       [0.0425897 ],
       [0.04318773],
       ...,
       [0.10208008],
       [0.09947998],
       [0.09869995]])

In [6]:
test

array([[0.09427977],
       [0.09557982],
       [0.09791992],
       ...,
       [0.11697868],
       [0.11661466],
       [0.11674467]])

In [7]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [8]:
train_X

array([[[0.04170567],
        [0.0425897 ],
        [0.04318773],
        ...,
        [0.04230369],
        [0.0425897 ],
        [0.04290172]],

       [[0.0425897 ],
        [0.04318773],
        [0.04235569],
        ...,
        [0.0425897 ],
        [0.04290172],
        [0.0423817 ]],

       [[0.04318773],
        [0.04235569],
        [0.0425117 ],
        ...,
        [0.04290172],
        [0.0423817 ],
        [0.04193968]],

       ...,

       [[0.11300052],
        [0.11300052],
        [0.11170047],
        ...,
        [0.09973999],
        [0.10104004],
        [0.10182007]],

       [[0.11300052],
        [0.11170047],
        [0.11274051],
        ...,
        [0.10104004],
        [0.10182007],
        [0.10208008]],

       [[0.11170047],
        [0.11274051],
        [0.11170047],
        ...,
        [0.10182007],
        [0.10208008],
        [0.09947998]]])

In [9]:
train_y

array([0.0423817 , 0.04193968, 0.04144566, ..., 0.10208008, 0.09947998,
       0.09869995])

In [10]:
test_X

array([[[0.09427977],
        [0.09557982],
        [0.09791992],
        ...,
        [0.09453978],
        [0.0973999 ],
        [0.09453978]],

       [[0.09557982],
        [0.09791992],
        [0.09635985],
        ...,
        [0.0973999 ],
        [0.09453978],
        [0.09479979]],

       [[0.09791992],
        [0.09635985],
        [0.0950598 ],
        ...,
        [0.09453978],
        [0.09479979],
        [0.09635985]],

       ...,

       [[0.11185647],
        [0.11066043],
        [0.11097244],
        ...,
        [0.11619865],
        [0.11677067],
        [0.1173947 ]],

       [[0.11066043],
        [0.11097244],
        [0.11102444],
        ...,
        [0.11677067],
        [0.1173947 ],
        [0.11697868]],

       [[0.11097244],
        [0.11102444],
        [0.11086843],
        ...,
        [0.1173947 ],
        [0.11697868],
        [0.11661466]]])

In [11]:
test_y

array([0.09479979, 0.09635985, 0.0973999 , ..., 0.11697868, 0.11661466,
       0.11674467])

In [12]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 1) (20994,) (5230, 25, 1) (5230,)


## Model Training

In [13]:
hyperparam = [(32,100,100)]

In [14]:
for batch, epoch, neuron in hyperparam:
    model1, bilstm1 = LSTMUnit.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)

Metal device set to: Apple M1
Epoch 1/100


2023-05-15 11:26:31.416706: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-05-15 11:26:31.416809: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-05-15 11:26:31.572259: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-05-15 11:26:32.901385: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-15 11:26:33.118983: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-15 11:26:33.144015: I tensorflow/core/grappler/o

657/657 - 19s - loss: 4.8453e-04 - val_loss: 1.3617e-04 - 19s/epoch - 28ms/step
Epoch 2/100
657/657 - 13s - loss: 6.8070e-04 - val_loss: 1.8961e-04 - 13s/epoch - 20ms/step
Epoch 3/100
657/657 - 13s - loss: 0.0012 - val_loss: 4.9871e-04 - 13s/epoch - 20ms/step
Epoch 4/100
657/657 - 13s - loss: 0.0015 - val_loss: 2.1992e-04 - 13s/epoch - 20ms/step
Epoch 5/100
657/657 - 13s - loss: 0.0013 - val_loss: 6.7396e-04 - 13s/epoch - 20ms/step
Epoch 6/100
657/657 - 13s - loss: 0.0012 - val_loss: 5.5366e-04 - 13s/epoch - 20ms/step
Epoch 7/100
657/657 - 13s - loss: 9.3531e-04 - val_loss: 3.6882e-04 - 13s/epoch - 20ms/step
Epoch 8/100
657/657 - 13s - loss: 7.5348e-04 - val_loss: 3.9107e-04 - 13s/epoch - 20ms/step
Epoch 9/100
657/657 - 13s - loss: 5.9784e-04 - val_loss: 2.3711e-04 - 13s/epoch - 20ms/step
Epoch 10/100
657/657 - 13s - loss: 4.5123e-04 - val_loss: 1.2449e-04 - 13s/epoch - 20ms/step
Epoch 11/100
657/657 - 13s - loss: 3.4004e-04 - val_loss: 7.3696e-05 - 13s/epoch - 20ms/step
Epoch 12/100
6

In [15]:
i=0
# make a prediction
test_x2 = test_X
yhat = LSTMUnit.predict(test_x2, model1)
inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
print(hyperparam[i])
print("Epoch: "+ str(bilstm1.params['epochs']))
print("Neurons: "+str(model1.layers[0].layer.units))
i = i+1
print('RMSE')
print(Evaluation.rmse(inv_y,inv_yhat))
print('MAE')
print(Evaluation.mae(inv_y,inv_yhat))
print('MAPE')
print(Evaluation.mape(inv_y,inv_yhat))
LSTMUnit.save_model(model1, 1, 'LTC',hyperparam[0])
with open('BiLSTM_LTC'+str(hyperparam[0])+'.pkl', 'wb') as f:
    pickle.dump(bilstm1.history, f)

  7/164 [>.............................] - ETA: 1s 

2023-05-15 11:50:15.641252: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-15 11:50:15.688722: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-15 11:50:15.697383: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 9ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
RMSE
0.679437502737191
MAE
0.49839320102202983
MAPE
0.8287721219630683
