In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
btc_dfd = pd.read_csv('../Dataset/Binance_BTCUSDT_1h.csv')
btc_dfd

Unix                 Date   Symbol      Open      High  \
0      1672527600000  2022-12-31 23:00:00  BTCUSDT  16520.28  16551.24   
1      1672524000000  2022-12-31 22:00:00  BTCUSDT  16548.28  16567.49   
2      1672520400000  2022-12-31 21:00:00  BTCUSDT  16568.19  16571.64   
3      1672516800000  2022-12-31 20:00:00  BTCUSDT  16570.14  16574.97   
4      1672513200000  2022-12-31 19:00:00  BTCUSDT  16577.78  16590.06   
...              ...                  ...      ...       ...       ...   
26269  1577851200000  2020-01-01 04:00:00  BTCUSDT   7225.00   7230.00   
26270  1577847600000  2020-01-01 03:00:00  BTCUSDT   7242.66   7245.00   
26271  1577844000000  2020-01-01 02:00:00  BTCUSDT   7215.52   7244.87   
26272  1577840400000  2020-01-01 01:00:00  BTCUSDT   7176.47   7230.00   
26273  1577836800000  2020-01-01 00:00:00  BTCUSDT   7195.24   7196.25   

            Low     Close   Volume BTC   Volume USDT  tradecount  
0      16487.74  16542.40  4973.433070  8.217183e+07      152632  
1      16470.00  16520.81  6695.136250  1.106669e+08      153933  
2      16544.12  16548.28  3618.773890  5.992803e+07      105065  
3      16564.09  16568.60  2622.143550  4.344849e+07       90705  
4      16565.10  16570.14  4044.433590  6.704605e+07      116587  
...         ...       ...          ...           ...         ...  
26269   7215.03   7217.27   467.812578  3.379094e+06        5896  
26270   7220.00   7225.01   783.724867  5.667367e+06        8337  
26271   7211.41   7242.85   655.156809  4.736719e+06        7466  
26272   7175.71   7216.27   883.052603  6.365953e+06        9033  
26273   7175.46   7177.02   511.814901  3.675857e+06        7640  

[26274 rows x 10 columns]

In [3]:
df_no_dup = Preprocessing.handle_duplicate(btc_dfd)
df_no_dup

duplicate ok


Unix                 Date   Symbol      Open      High  \
0      1672527600000  2022-12-31 23:00:00  BTCUSDT  16520.28  16551.24   
1      1672524000000  2022-12-31 22:00:00  BTCUSDT  16548.28  16567.49   
2      1672520400000  2022-12-31 21:00:00  BTCUSDT  16568.19  16571.64   
3      1672516800000  2022-12-31 20:00:00  BTCUSDT  16570.14  16574.97   
4      1672513200000  2022-12-31 19:00:00  BTCUSDT  16577.78  16590.06   
...              ...                  ...      ...       ...       ...   
26269  1577851200000  2020-01-01 04:00:00  BTCUSDT   7225.00   7230.00   
26270  1577847600000  2020-01-01 03:00:00  BTCUSDT   7242.66   7245.00   
26271  1577844000000  2020-01-01 02:00:00  BTCUSDT   7215.52   7244.87   
26272  1577840400000  2020-01-01 01:00:00  BTCUSDT   7176.47   7230.00   
26273  1577836800000  2020-01-01 00:00:00  BTCUSDT   7195.24   7196.25   

            Low     Close   Volume BTC   Volume USDT  tradecount  
0      16487.74  16542.40  4973.433070  8.217183e+07      152632  
1      16470.00  16520.81  6695.136250  1.106669e+08      153933  
2      16544.12  16548.28  3618.773890  5.992803e+07      105065  
3      16564.09  16568.60  2622.143550  4.344849e+07       90705  
4      16565.10  16570.14  4044.433590  6.704605e+07      116587  
...         ...       ...          ...           ...         ...  
26269   7215.03   7217.27   467.812578  3.379094e+06        5896  
26270   7220.00   7225.01   783.724867  5.667367e+06        8337  
26271   7211.41   7242.85   655.156809  4.736719e+06        7466  
26272   7175.71   7216.27   883.052603  6.365953e+06        9033  
26273   7175.46   7177.02   511.814901  3.675857e+06        7640  

[26274 rows x 10 columns]

In [4]:
df = Preprocessing.feature_selection(df_no_dup)
df

Close
0       7177.02
1       7216.27
2       7242.85
3       7225.01
4       7217.27
...         ...
26269  16570.14
26270  16568.60
26271  16548.28
26272  16520.81
26273  16542.40

[26274 rows x 1 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df)
miss

No missing value


Close
0       7177.02
1       7216.27
2       7242.85
3       7225.01
4       7217.27
...         ...
26269  16570.14
26270  16568.60
26271  16548.28
26272  16520.81
26273  16542.40

[26274 rows x 1 columns]

In [6]:
x, scaler = Preprocessing.minmax_scale(miss)
x

array([[0.04722846],
       [0.04783696],
       [0.04824904],
       ...,
       [0.19251245],
       [0.19208658],
       [0.19242129]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04722846],
       [0.04783696],
       [0.04824904],
       ...,
       [0.39344233],
       [0.3886748 ],
       [0.38670838]])

In [8]:
test

array([[0.38493033],
       [0.38538193],
       [0.38586346],
       ...,
       [0.19251245],
       [0.19208658],
       [0.19242129]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,50)
test_X, test_y = Preprocessing.create_dataset(test,50)

In [10]:
train_X

array([[[0.04722846],
        [0.04783696],
        [0.04824904],
        ...,
        [0.0439525 ],
        [0.0435074 ],
        [0.04276092]],

       [[0.04783696],
        [0.04824904],
        [0.04797246],
        ...,
        [0.0435074 ],
        [0.04276092],
        [0.0438156 ]],

       [[0.04824904],
        [0.04797246],
        [0.04785247],
        ...,
        [0.04276092],
        [0.0438156 ],
        [0.04374057]],

       ...,

       [[0.39273042],
        [0.39464987],
        [0.39494194],
        ...,
        [0.39144071],
        [0.39268484],
        [0.39452832]],

       [[0.39464987],
        [0.39494194],
        [0.39570129],
        ...,
        [0.39268484],
        [0.39452832],
        [0.39344233]],

       [[0.39494194],
        [0.39570129],
        [0.39524596],
        ...,
        [0.39452832],
        [0.39344233],
        [0.3886748 ]]])

In [11]:
train_y

array([0.0438156 , 0.04374057, 0.0477427 , ..., 0.39344233, 0.3886748 ,
       0.38670838])

In [12]:
test_X

array([[[0.38493033],
        [0.38538193],
        [0.38586346],
        ...,
        [0.38563804],
        [0.38440368],
        [0.38406695]],

       [[0.38538193],
        [0.38586346],
        [0.38442601],
        ...,
        [0.38440368],
        [0.38406695],
        [0.38531015]],

       [[0.38586346],
        [0.38442601],
        [0.38245246],
        ...,
        [0.38406695],
        [0.38531015],
        [0.38463995]],

       ...,

       [[0.19350651],
        [0.19330249],
        [0.19330714],
        ...,
        [0.19296994],
        [0.19285135],
        [0.19282747]],

       [[0.19330249],
        [0.19330714],
        [0.19361751],
        ...,
        [0.19285135],
        [0.19282747],
        [0.19251245]],

       [[0.19330714],
        [0.19361751],
        [0.19383316],
        ...,
        [0.19282747],
        [0.19251245],
        [0.19208658]]])

In [13]:
test_y

array([0.38531015, 0.38463995, 0.38622127, ..., 0.19251245, 0.19208658,
       0.19242129])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20969, 50, 1) (20969,) (5205, 50, 1) (5205,)


## Model Training

In [15]:
hyperparam = [(64,100,60)]

In [16]:
for batch, epoch, neuron in hyperparam:
    model1, bilstm1 = LSTMUnit.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)

Metal device set to: Apple M1
Epoch 1/100


2023-04-07 21:34:21.009192: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-07 21:34:21.009635: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-04-07 21:34:21.169863: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-04-07 21:34:22.143112: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 21:34:22.294688: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 21:34:22.306947: I tensorflow/core/grappler/o

328/328 - 12s - loss: 8.6421e-04 - val_loss: 0.0015 - 12s/epoch - 38ms/step
Epoch 2/100
328/328 - 10s - loss: 9.1106e-04 - val_loss: 0.0017 - 10s/epoch - 31ms/step
Epoch 3/100
328/328 - 10s - loss: 8.3935e-04 - val_loss: 0.0019 - 10s/epoch - 31ms/step
Epoch 4/100
328/328 - 11s - loss: 8.5999e-04 - val_loss: 0.0022 - 11s/epoch - 33ms/step
Epoch 5/100
328/328 - 10s - loss: 9.2709e-04 - val_loss: 0.0026 - 10s/epoch - 31ms/step
Epoch 6/100
328/328 - 10s - loss: 0.0011 - val_loss: 0.0031 - 10s/epoch - 31ms/step
Epoch 7/100
328/328 - 10s - loss: 0.0012 - val_loss: 0.0036 - 10s/epoch - 30ms/step
Epoch 8/100
328/328 - 10s - loss: 0.0012 - val_loss: 0.0039 - 10s/epoch - 31ms/step
Epoch 9/100
328/328 - 10s - loss: 0.0013 - val_loss: 0.0042 - 10s/epoch - 31ms/step
Epoch 10/100
328/328 - 10s - loss: 0.0013 - val_loss: 0.0042 - 10s/epoch - 30ms/step
Epoch 11/100
328/328 - 10s - loss: 0.0012 - val_loss: 0.0041 - 10s/epoch - 30ms/step
Epoch 12/100
328/328 - 10s - loss: 0.0011 - val_loss: 0.0040 - 10s

In [17]:
i=0
# make a prediction
test_x2 = test_X
yhat = LSTMUnit.predict(test_x2, model1)
inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
print(hyperparam[i])
print("Epoch: "+ str(bilstm1.params['epochs']))
print("Neurons: "+str(model1.layers[0].layer.units))
i = i+1
print('RMSE')
print(Evaluation.rmse(inv_y,inv_yhat))
print('MAE')
print(Evaluation.mae(inv_y,inv_yhat))
print('MAPE')
print(Evaluation.mape(inv_y,inv_yhat))
LSTMUnit.save_model(model1, 1, 'BTC',hyperparam[0])
with open('BiLSTM_BTC'+str(hyperparam[0])+'.pkl', 'wb') as f:
    pickle.dump(bilstm1.history, f)

2023-04-07 21:50:56.201904: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 21:50:56.282454: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 21:50:56.292195: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


163/163 [==============================] - 3s 15ms/step
(64, 100, 60)
Epoch: 100
Neurons: 60
RMSE
404.9157953045415
MAE
370.59257451518965
MAPE
1.9343348554006254
