In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
eth_dfd = pd.read_csv('../Dataset/Binance_ETHUSDT_1h.csv')
eth_dfd

Date     Open     High      Low    Close   Volume USDT
0      2022-12-31 23:00:00  1196.18  1197.43  1193.60  1196.13  7.086714e+06
1      2022-12-31 22:00:00  1200.09  1201.11  1193.08  1196.19  1.143952e+07
2      2022-12-31 21:00:00  1202.33  1203.00  1199.83  1200.10  4.643401e+06
3      2022-12-31 20:00:00  1202.66  1203.71  1202.30  1202.34  4.278879e+06
4      2022-12-31 19:00:00  1199.59  1205.61  1199.42  1202.65  7.738029e+06
...                    ...      ...      ...      ...      ...           ...
26269  2020-01-01 04:00:00   130.21   130.74   130.15   130.20  4.430067e+05
26270  2020-01-01 03:00:00   130.85   130.89   129.94   130.20  6.473610e+05
26271  2020-01-01 02:00:00   130.63   130.98   130.35   130.85  9.940256e+05
26272  2020-01-01 01:00:00   128.87   130.65   128.78   130.64  1.474278e+06
26273  2020-01-01 00:00:00   129.16   129.19   128.68   128.87  1.000930e+06

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(eth_dfd)
df

Close
0       128.87
1       130.64
2       130.85
3       130.20
4       130.20
...        ...
26269  1202.65
26270  1202.34
26271  1200.10
26272  1196.19
26273  1196.13

[26274 rows x 1 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.00678935],
       [0.00716197],
       [0.00720618],
       ...,
       [0.23230718],
       [0.23148404],
       [0.2314714 ]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.00678935],
       [0.00716197],
       [0.00720618],
       ...,
       [0.36294049],
       [0.35696376],
       [0.35310278]])

In [6]:
test

array([[0.34664396],
       [0.34877655],
       [0.35186281],
       ...,
       [0.23230718],
       [0.23148404],
       [0.2314714 ]])

In [7]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [8]:
train_X

array([[[0.00678935],
        [0.00716197],
        [0.00720618],
        ...,
        [0.00708408],
        [0.00718934],
        [0.00716829]],

       [[0.00716197],
        [0.00720618],
        [0.00706934],
        ...,
        [0.00718934],
        [0.00716829],
        [0.00705881]],

       [[0.00720618],
        [0.00706934],
        [0.00706934],
        ...,
        [0.00716829],
        [0.00705881],
        [0.00696829]],

       ...,

       [[0.39394411],
        [0.39336939],
        [0.38862632],
        ...,
        [0.36419099],
        [0.36438046],
        [0.36570254]],

       [[0.39336939],
        [0.38862632],
        [0.39214836],
        ...,
        [0.36438046],
        [0.36570254],
        [0.36294049]],

       [[0.38862632],
        [0.39214836],
        [0.38899684],
        ...,
        [0.36570254],
        [0.36294049],
        [0.35696376]]])

In [9]:
train_y

array([0.00705881, 0.00696829, 0.00683777, ..., 0.36294049, 0.35696376,
       0.35310278])

In [10]:
test_X

array([[[0.34664396],
        [0.34877655],
        [0.35186281],
        ...,
        [0.34328823],
        [0.34773236],
        [0.34391769]],

       [[0.34877655],
        [0.35186281],
        [0.34708184],
        ...,
        [0.34773236],
        [0.34391769],
        [0.34373243]],

       [[0.35186281],
        [0.34708184],
        [0.34520188],
        ...,
        [0.34391769],
        [0.34373243],
        [0.35124808]],

       ...,

       [[0.23174087],
        [0.23192192],
        [0.23190718],
        ...,
        [0.23220192],
        [0.23284401],
        [0.23277875]],

       [[0.23192192],
        [0.23190718],
        [0.23228402],
        ...,
        [0.23284401],
        [0.23277875],
        [0.23230718]],

       [[0.23190718],
        [0.23228402],
        [0.23174087],
        ...,
        [0.23277875],
        [0.23230718],
        [0.23148404]]])

In [11]:
test_y

array([0.34373243, 0.35124808, 0.35062494, ..., 0.23230718, 0.23148404,
       0.2314714 ])

In [12]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 1) (20994,) (5230, 25, 1) (5230,)


## Model Training

In [13]:
hyperparam = [(32,100,100)]

In [14]:
for batch, epoch, neuron in hyperparam:
    model1, lstm1 = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)

Metal device set to: Apple M1


2023-05-14 23:00:40.279969: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-05-14 23:00:40.280065: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/100


2023-05-14 23:00:40.529860: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-05-14 23:00:40.963578: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:00:41.052922: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:00:41.382417: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:00:49.153651: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:00:49.186122: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 10s - loss: 4.5502e-04 - val_loss: 0.0018 - 10s/epoch - 15ms/step
Epoch 2/100
657/657 - 8s - loss: 7.6062e-04 - val_loss: 0.0016 - 8s/epoch - 13ms/step
Epoch 3/100
657/657 - 8s - loss: 8.7436e-04 - val_loss: 0.0019 - 8s/epoch - 12ms/step
Epoch 4/100
657/657 - 9s - loss: 9.2871e-04 - val_loss: 0.0024 - 9s/epoch - 13ms/step
Epoch 5/100
657/657 - 9s - loss: 9.7602e-04 - val_loss: 0.0029 - 9s/epoch - 13ms/step
Epoch 6/100
657/657 - 8s - loss: 9.7669e-04 - val_loss: 0.0026 - 8s/epoch - 12ms/step
Epoch 7/100
657/657 - 8s - loss: 8.1850e-04 - val_loss: 0.0021 - 8s/epoch - 13ms/step
Epoch 8/100
657/657 - 8s - loss: 6.7330e-04 - val_loss: 0.0015 - 8s/epoch - 13ms/step
Epoch 9/100
657/657 - 8s - loss: 5.4491e-04 - val_loss: 0.0010 - 8s/epoch - 13ms/step
Epoch 10/100
657/657 - 8s - loss: 4.1936e-04 - val_loss: 6.4033e-04 - 8s/epoch - 13ms/step
Epoch 11/100
657/657 - 8s - loss: 3.2484e-04 - val_loss: 3.9973e-04 - 8s/epoch - 13ms/step
Epoch 12/100
657/657 - 8s - loss: 2.5672e-04 - val_los

In [15]:
i=0
# make a prediction
test_x2 = test_X
yhat = LSTMUnit.predict(test_x2, model1)
inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
print(hyperparam[i])
print("Epoch: "+ str(lstm1.params['epochs']))
print("Neurons: "+str(model1.layers[0].units))
print('RMSE')
print(Evaluation.rmse(inv_y,inv_yhat))
print('MAE')
print(Evaluation.mae(inv_y,inv_yhat))
print('MAPE')
print(Evaluation.mape(inv_y,inv_yhat))
LSTMUnit.save_model(model1, 0, 'ETH',hyperparam[0])
with open('LSTM_ETH'+str(hyperparam[0])+'.pkl', 'wb') as f:
        pickle.dump(lstm1.history, f)

 11/164 [=>............................] - ETA: 0s 

2023-05-14 23:13:57.885943: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:13:57.918133: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 5ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
RMSE
23.307975042283243
MAE
20.632411088465762
MAPE
1.5155344242331603
