In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
ltc_dfd = pd.read_csv('../Dataset/Binance_LTCUSDT_1h.csv')
ltc_dfd

Date   Open   High    Low  Close   Volume USDT
0      2022-12-31 23:00:00  70.08  70.30  69.79  70.14  9.486568e+05
1      2022-12-31 22:00:00  70.24  70.24  69.71  70.09  8.838422e+05
2      2022-12-31 21:00:00  70.40  70.45  70.19  70.23  6.820723e+05
3      2022-12-31 20:00:00  70.15  70.53  70.08  70.39  1.173164e+06
4      2022-12-31 19:00:00  69.93  70.32  69.93  70.15  9.964355e+05
...                    ...    ...    ...    ...    ...           ...
26269  2020-01-01 04:00:00  41.53  41.85  41.45  41.59  2.214516e+05
26270  2020-01-01 03:00:00  41.84  41.85  41.49  41.53  1.613043e+05
26271  2020-01-01 02:00:00  41.63  41.88  41.62  41.85  2.402871e+05
26272  2020-01-01 01:00:00  41.28  41.70  41.27  41.62  2.830715e+05
26273  2020-01-01 00:00:00  41.29  41.29  41.16  41.28  1.165827e+05

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(ltc_dfd)
df

Close
0      41.28
1      41.62
2      41.85
3      41.53
4      41.59
...      ...
26269  70.15
26270  70.39
26271  70.23
26272  70.09
26273  70.14

[26274 rows x 1 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x.shape

(26274, 1)

In [5]:
train, test = Preprocessing.splitting_data(x)
train.shape

(21019, 1)

In [6]:
test

array([[0.09427977],
       [0.09557982],
       [0.09791992],
       ...,
       [0.11697868],
       [0.11661466],
       [0.11674467]])

In [7]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [8]:
train_X.shape

(20994, 25, 1)

In [9]:
train_y

array([0.0423817 , 0.04193968, 0.04144566, ..., 0.10208008, 0.09947998,
       0.09869995])

In [10]:
test_X

array([[[0.09427977],
        [0.09557982],
        [0.09791992],
        ...,
        [0.09453978],
        [0.0973999 ],
        [0.09453978]],

       [[0.09557982],
        [0.09791992],
        [0.09635985],
        ...,
        [0.0973999 ],
        [0.09453978],
        [0.09479979]],

       [[0.09791992],
        [0.09635985],
        [0.0950598 ],
        ...,
        [0.09453978],
        [0.09479979],
        [0.09635985]],

       ...,

       [[0.11185647],
        [0.11066043],
        [0.11097244],
        ...,
        [0.11619865],
        [0.11677067],
        [0.1173947 ]],

       [[0.11066043],
        [0.11097244],
        [0.11102444],
        ...,
        [0.11677067],
        [0.1173947 ],
        [0.11697868]],

       [[0.11097244],
        [0.11102444],
        [0.11086843],
        ...,
        [0.1173947 ],
        [0.11697868],
        [0.11661466]]])

In [11]:
test_y

array([0.09479979, 0.09635985, 0.0973999 , ..., 0.11697868, 0.11661466,
       0.11674467])

In [12]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 1) (20994,) (5230, 25, 1) (5230,)


## Model Training

In [13]:
hyperparam = [(32,100,60)]

In [14]:
for batch, epoch, neuron in hyperparam:
    model1, lstm1 = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)

Metal device set to: Apple M1


2023-05-14 23:08:03.812572: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-05-14 23:08:03.812861: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/100


2023-05-14 23:08:04.159775: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-05-14 23:08:04.612825: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:08:04.731091: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:08:05.620096: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:08:14.164896: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:08:14.197498: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 11s - loss: 3.2708e-04 - val_loss: 1.0887e-04 - 11s/epoch - 17ms/step
Epoch 2/100
657/657 - 8s - loss: 5.3929e-04 - val_loss: 2.5150e-04 - 8s/epoch - 12ms/step
Epoch 3/100
657/657 - 8s - loss: 0.0012 - val_loss: 6.4401e-04 - 8s/epoch - 12ms/step
Epoch 4/100
657/657 - 8s - loss: 0.0011 - val_loss: 8.5717e-04 - 8s/epoch - 12ms/step
Epoch 5/100
657/657 - 8s - loss: 8.5819e-04 - val_loss: 6.5485e-04 - 8s/epoch - 12ms/step
Epoch 6/100
657/657 - 8s - loss: 6.6530e-04 - val_loss: 3.9026e-04 - 8s/epoch - 12ms/step
Epoch 7/100
657/657 - 8s - loss: 4.9280e-04 - val_loss: 2.0994e-04 - 8s/epoch - 12ms/step
Epoch 8/100
657/657 - 9s - loss: 3.5598e-04 - val_loss: 1.0620e-04 - 9s/epoch - 13ms/step
Epoch 9/100
657/657 - 8s - loss: 2.6342e-04 - val_loss: 6.0019e-05 - 8s/epoch - 12ms/step
Epoch 10/100
657/657 - 8s - loss: 2.0532e-04 - val_loss: 3.9312e-05 - 8s/epoch - 12ms/step
Epoch 11/100
657/657 - 8s - loss: 1.7100e-04 - val_loss: 3.0409e-05 - 8s/epoch - 12ms/step
Epoch 12/100
657/657 - 8s 

In [15]:
i=0
# make a prediction
test_x2 = test_X
yhat = LSTMUnit.predict(test_x2, model1)
inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
print(hyperparam[i])
print("Epoch: "+ str(lstm1.params['epochs']))
print("Neurons: "+str(model1.layers[0].units))
print('RMSE')
print(Evaluation.rmse(inv_y,inv_yhat))
print('MAE')
print(Evaluation.mae(inv_y,inv_yhat))
print('MAPE')
print(Evaluation.mape(inv_y,inv_yhat))
LSTMUnit.save_model(model1, 0, 'LTC',hyperparam[0])
with open('LSTM_LTC'+str(hyperparam[0])+'.pkl', 'wb') as f:
    pickle.dump(lstm1.history, f)

 26/164 [===>..........................] - ETA: 0s

2023-05-14 23:20:21.278134: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-14 23:20:21.304823: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 1s 4ms/step
(32, 100, 60)
Epoch: 100
Neurons: 60
RMSE
0.8588553422994142
MAE
0.6420822860396845
MAPE
1.0317123783557842
