In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import NeuralNetwork
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [2]:
btc_dfd = pd.read_csv('../Dataset/Binance_BTCUSDT_1h.csv')
btc_dfd

Date      Open      High       Low     Close  \
0      2022-12-31 23:00:00  16520.28  16551.24  16487.74  16542.40   
1      2022-12-31 22:00:00  16548.28  16567.49  16470.00  16520.81   
2      2022-12-31 21:00:00  16568.19  16571.64  16544.12  16548.28   
3      2022-12-31 20:00:00  16570.14  16574.97  16564.09  16568.60   
4      2022-12-31 19:00:00  16577.78  16590.06  16565.10  16570.14   
...                    ...       ...       ...       ...       ...   
26269  2020-01-01 04:00:00   7225.00   7230.00   7215.03   7217.27   
26270  2020-01-01 03:00:00   7242.66   7245.00   7220.00   7225.01   
26271  2020-01-01 02:00:00   7215.52   7244.87   7211.41   7242.85   
26272  2020-01-01 01:00:00   7176.47   7230.00   7175.71   7216.27   
26273  2020-01-01 00:00:00   7195.24   7196.25   7175.46   7177.02   

        Volume USDT  
0      8.217183e+07  
1      1.106669e+08  
2      5.992803e+07  
3      4.344849e+07  
4      6.704605e+07  
...             ...  
26269  3.379094e+06  
26270  5.667367e+06  
26271  4.736719e+06  
26272  6.365953e+06  
26273  3.675857e+06  

[26274 rows x 6 columns]

In [3]:
df = Preprocessing.sort_df(btc_dfd)
df

Close
0       7177.02
1       7216.27
2       7242.85
3       7225.01
4       7217.27
...         ...
26269  16570.14
26270  16568.60
26271  16548.28
26272  16520.81
26273  16542.40

[26274 rows x 1 columns]

In [4]:
x, scaler = Preprocessing.minmax_scale(df)
x

array([[0.04722846],
       [0.04783696],
       [0.04824904],
       ...,
       [0.19251245],
       [0.19208658],
       [0.19242129]])

In [5]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04722846],
       [0.04783696],
       [0.04824904],
       ...,
       [0.39344233],
       [0.3886748 ],
       [0.38670838]])

In [6]:
test

array([[0.38493033],
       [0.38538193],
       [0.38586346],
       ...,
       [0.19251245],
       [0.19208658],
       [0.19242129]])

In [7]:
train_X, train_y = Preprocessing.create_dataset(train,25)
test_X, test_y = Preprocessing.create_dataset(test,25)

In [8]:
train_X

array([[[0.04722846],
        [0.04783696],
        [0.04824904],
        ...,
        [0.04755357],
        [0.0475979 ],
        [0.04775557]],

       [[0.04783696],
        [0.04824904],
        [0.04797246],
        ...,
        [0.0475979 ],
        [0.04775557],
        [0.04744504]],

       [[0.04824904],
        [0.04797246],
        [0.04785247],
        ...,
        [0.04775557],
        [0.04744504],
        [0.04710444]],

       ...,

       [[0.39834302],
        [0.39773174],
        [0.39395827],
        ...,
        [0.39144071],
        [0.39268484],
        [0.39452832]],

       [[0.39773174],
        [0.39395827],
        [0.39775096],
        ...,
        [0.39268484],
        [0.39452832],
        [0.39344233]],

       [[0.39395827],
        [0.39775096],
        [0.39605305],
        ...,
        [0.39452832],
        [0.39344233],
        [0.3886748 ]]])

In [9]:
train_y

array([0.04744504, 0.04710444, 0.04649346, ..., 0.39344233, 0.3886748 ,
       0.38670838])

In [10]:
test_X

array([[[0.38493033],
        [0.38538193],
        [0.38586346],
        ...,
        [0.37981398],
        [0.38255028],
        [0.37959724]],

       [[0.38538193],
        [0.38586346],
        [0.38442601],
        ...,
        [0.38255028],
        [0.37959724],
        [0.38068448]],

       [[0.38586346],
        [0.38442601],
        [0.38245246],
        ...,
        [0.37959724],
        [0.38068448],
        [0.38275027]],

       ...,

       [[0.19282887],
        [0.19308265],
        [0.1930549 ],
        ...,
        [0.19296994],
        [0.19285135],
        [0.19282747]],

       [[0.19308265],
        [0.1930549 ],
        [0.19343023],
        ...,
        [0.19285135],
        [0.19282747],
        [0.19251245]],

       [[0.1930549 ],
        [0.19343023],
        [0.19300917],
        ...,
        [0.19282747],
        [0.19251245],
        [0.19208658]]])

In [11]:
test_y

array([0.38068448, 0.38275027, 0.38296623, ..., 0.19251245, 0.19208658,
       0.19242129])

In [12]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20994, 25, 1) (20994,) (5230, 25, 1) (5230,)


## Model Training

In [13]:
hyperparam = [(16,50,60)]

In [14]:
for batch, epoch, neuron in hyperparam:
    model1, lstm1 = NeuralNetwork.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)

Metal device set to: Apple M1


2023-06-16 21:14:32.532794: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-06-16 21:14:32.533221: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/50


2023-06-16 21:14:32.844828: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-06-16 21:14:33.257317: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 21:14:33.349217: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 21:14:33.503181: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 21:14:48.146056: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 21:14:48.180604: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1313/1313 - 17s - loss: 2.0452e-04 - val_loss: 0.0045 - 17s/epoch - 13ms/step
Epoch 2/50
1313/1313 - 16s - loss: 2.6978e-04 - val_loss: 0.0054 - 16s/epoch - 12ms/step
Epoch 3/50
1313/1313 - 20s - loss: 3.4142e-04 - val_loss: 0.0053 - 20s/epoch - 15ms/step
Epoch 4/50
1313/1313 - 21s - loss: 3.4281e-04 - val_loss: 0.0046 - 21s/epoch - 16ms/step
Epoch 5/50
1313/1313 - 21s - loss: 3.0937e-04 - val_loss: 0.0040 - 21s/epoch - 16ms/step
Epoch 6/50
1313/1313 - 21s - loss: 2.6230e-04 - val_loss: 0.0034 - 21s/epoch - 16ms/step
Epoch 7/50
1313/1313 - 22s - loss: 2.1241e-04 - val_loss: 0.0028 - 22s/epoch - 17ms/step
Epoch 8/50
1313/1313 - 22s - loss: 1.7183e-04 - val_loss: 0.0023 - 22s/epoch - 17ms/step
Epoch 9/50
1313/1313 - 23s - loss: 1.4569e-04 - val_loss: 0.0019 - 23s/epoch - 18ms/step
Epoch 10/50
1313/1313 - 23s - loss: 1.2245e-04 - val_loss: 0.0016 - 23s/epoch - 18ms/step
Epoch 11/50
1313/1313 - 23s - loss: 1.1013e-04 - val_loss: 0.0013 - 23s/epoch - 18ms/step
Epoch 12/50
1313/1313 - 24s - 

In [15]:
i=0
# make a prediction
test_x2 = test_X
yhat = NeuralNetwork.predict(test_x2, model1)
inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
print(hyperparam[i])
print("Epoch: "+ str(lstm1.params['epochs']))
print("Neurons: "+str(model1.layers[0].units))
i = i+1
print('RMSE')
print(Evaluation.rmse(inv_y,inv_yhat))
print('MAE')
print(Evaluation.mae(inv_y,inv_yhat))
print('MAPE')
print(Evaluation.mape(inv_y,inv_yhat))
NeuralNetwork.save_model(model1, 0, 'BTC',hyperparam[0])
with open('LSTM_BTC'+str(hyperparam[0])+'.pkl', 'wb') as f:
    pickle.dump(lstm1.history, f)

2023-06-16 21:34:18.742394: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-16 21:34:18.839483: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


164/164 [==============================] - 2s 8ms/step
(16, 50, 60)
Epoch: 50
Neurons: 60
RMSE
962.6578798607347
MAE
924.5501534715596
MAPE
4.7693115280888865
